const arrivalEvents = [
	'<li><span class="local-event-destiny-required">ATTENTION, CAPTAIN:</span> Imperial Starbase and/or Fleet nearby.</li>',
	'<li><span class="local-event-destiny-required">ATTENTION, CAPTAIN:</span> Imperial Customs is active in the area.</li>',
	'<li><span class="local-event-destiny-required">ATTENTION, CAPTAIN:</span> Fugitives being sought by Imperial Procurator and/or IOCI forces in the area.</li>',
	'<li><span class="local-event-destiny-required">ATTENTION, CAPTAIN:</span> Bureau of Ships & Services (BoSS) has a checkpoint nearby. You may be asked for your BoSS Datapad.</li>',
	'<li><span class="local-event-destiny-required">A DISTURBANCE IN THE FORCE:</span> All PCs gain 1 Force Die while in the system, but only <span style="background-color:black;color:red">Dark Side</span> pips may be used for successes.</li>',
];

const localEmpireEvents = [
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Stealth check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Streetwise check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Computers check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Education check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Education check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Streetwise check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Core Worlds check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Core Worlds check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Underworld check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Computers check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Core Worlds check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Underworld check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Computers check(s).</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on weapons.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on armor.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on ship components.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on cybernetics.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Maintenance crew at work in the area.</li>',
	'<li><span class="local-event-free">RUSH HOUR:</span> Vehicle/Foot traffic higher (+<span class="font-normal starwars-dice setback">s</span>) than normal.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Law enforcement has locked down an important location.</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Charm check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Coercion check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Computers check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Deception check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Mechanics check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Medicine check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Negotiation check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Streetwise check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Survival check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Vigilance check(s).</li>',
	'<li><span class="local-event-free">NEW SHERIFF:</span> Local leadership takes an interest in you.</li>',
	'<li><span class="local-event-free">SEE "EM COMING:</span> +<span class="font-normal starwars-dice boost">b</span> to Piloting vs. spaceborne megafauna.</li>',
	'<li><span class="local-event-destiny-optional">LOOT ALERT:</span> Sensors indicate a debris field nearby.</li>',
	'<li><span class="local-event-destiny-optional">LOOT ALERT:</span> Sensors indicate a derelict spaceship nearby.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL EXPERT:</span> +<span class="font-normal starwars-dice boost">b</span> to Xenology regarding local flora and fauna.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on weapons.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on armor.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on survival gear.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on ship parts.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on riding beasts.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on landspeeders.</li>',
	'<li><span class="local-event-free">FESTIVAL:</span> A local entertainment event draws crowds.</li>',
	'<li><span class="local-event-free">POLITICAL STRIFE:</span> Tensions are running high.</li>',
	'<li><span class="local-event-free">LOCAL WEATHER:</span> Sensors indicate a storm on the horizon.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Adorable local urchins mob you for credits and candy. But they see <em>everything</em>.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> The local politician greets you at the landing site.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> You get the sensation you are being watched.</li>',
	'<li><span class="local-event-free">ATTENTION, SPACER:</span> You have an urgent message on GalactiMail.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Local prostitutes are very aggressive.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> <i>"You simply <em>have</em> to try the latest fad. Everyone\'s doing it!"</i></li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Mechanic.</i>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Slicer.</i>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Doctor.</i>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Scout.</i>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Core Worlds expert.</i>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Education expert.</i>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Lore expert.</i>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Outer Rim expert.</i>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Underworld expert.</i>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Warfare expert.</i>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Xenology expert.</i>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> <i>"Psst! I got a new kind of Spice that will rock your world."</i>',
	'<li><span class="local-event-destiny-optional">AN OLD FRIEND:</span> My juvenile delinquent buddy is working for law enforcement now???</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> An antiquities dealer wishes to speak to you. Come to the back door of the shop.</i>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> A "political prisoner" desperately needs to get off world. They can pay.</i>',
	'<li><span class="local-event-free">IMPERIAL CHECKPOINT:</span> <i>"Move it along, citizen. Declare any contraband <em>before</em> you get to the scanner. Move it along."</i></li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A crowd gathers around a passionate speech being made.</li>',
	'<li><span class="local-event-free">IMPERIAL CHECKPOINT:</span> <i>"You there! Citizen, stop! Have you seen this droid?"</i></li>',
];

const localOldWestEvents = [
	'<li><span class="local-event-free">ATTENTION, CAPTAIN:</span> Potential megafauna in the area.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on weapons.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on armor.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on survival gear.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on ship parts.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on riding beasts.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on landspeeders.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> The starport is experiencing an outage of some important service.</li>',
	'<li><span class="local-event-destiny-optional">ATTENTION, SPACER:</span> You run into an old friend. Do you think they have forgiven you yet?</li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> People are desperate for starship parts and will try to steal them off your ship.</li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> Pickpockets have been reported in the area recently.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> Due to recent circumstances, all nonsapient droids MUST have a restraining bolt.</i>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> Due to recent circumstances, droids are considered unwelcome in some establishments.</i>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> Due to recent circumstances, cybernetics are considered unwelcome in some establishments.</i>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Due to recent events, droids are considered mildly popular.</i>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Due to recent events, cybernetics are considered mildly popular.</i>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A small domesticated creature takes a liking to you.</i>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> The sky is full of (meteors, strange clouds, flying creatures, ...)</i>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> A fresh bloodstain is visible on the ground near your ship.</i>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> You are cordially invited to a gambling event.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> <em><b>Wanted:</b></em> Fearless PodRacer Jockeys and mechanics for the local podraces.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> <i>"Say, that\'s a shiny ship you got there. Is she for sale?"</i></li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> <i>"How much you want for that droid?"</i></li>',
	'<li><span class="local-event-free">ATTENTION, PILOT:</span> A local hotshot challenges you to a race.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A merchant requests your assistance with a local thief.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A thief requests your assistance with a local merchant.</i>',
	'<li><span class="local-event-destiny-optional">ATTENTION, CAPTAIN:</span> Sensors indicate a possible hideout in this system (+<span class="font-normal starwars-dice setback" >s</span> to be detected).</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Everyone seems to be looking at you curiously.</li>',
	'<li><span class="local-event-free">ATTENTION, CAPTAIN:</span> Small animal detected clinging to the hull. Is it friendly or hungry?</li>',
	'<li><span class="local-event-free">FESTIVAL:</span> A food festival promises large crowds.</li>',
	'<li><span class="local-event-free">NEW TAXES:</span> Spaceport fees halved/doubled.</li>',
	'<li><span class="local-event-free">ATTENTION, GUNNER:</span> A local wealthy scion challenges you to a duel. Do you want to "make it interesting"?</li>',
	'<li><span class="local-event-free">ATTENTION, DIPLOMAT:</span> An impoverished and troddendown local family needs your help with local law enforcement.</li>',
	'<li><span class="local-event-free">ATTENTION, DIPLOMAT:</span> Local law enforcement needs your help apprehending a brutal local crime family.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Did you hear something in the cargo hold?</li>',
	'<li><span class="local-event-free">ATTENTION, MECHANIC:</span> You find a stowaway hiding in the engine room.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Rumors abound of an insane old wizard living in the hills.</li>',
	'<li><span class="local-event-destiny-optional">ATTENTION, SLICER:</span> With a little "creative recordkeeping", starport fees might be "waived".</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Swoop bike races promise easy money (~10-100cr) for talented drivers and gamblers.</li>',
	'<li><span class="local-event-destiny-optional">AN OLD FRIEND:</span> Hey, my buddy works at the starport! They are a talented...(+<span class="font-normal starwars-dice boost">b</span> to one chosen skill)</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> You witness a local crime. The perp got away but you know where they are.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> You come across blackmail material against a local politician.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Fuel Shortage. Riding beasts are the way to go until something is done.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> Local farm/shop requests your assistance with a brutal gang.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> Local "militia" requests your assistance collecting "protection fees".</li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> <i>"My friend says he doesn\'t like you. <i><em>I</em></i> don\'t like you either."</i></li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> <i>"Hey! You can\'t bring that thing in here!"</i></li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> <i>"Check yer weapons at the door. We\'ve had trouble recently."</i></li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> Scorch marks on (another ship, the starport, a local business, ...)</li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> <i>"My friend says you owe him twenty credits. He says I get half."</i></li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> Something is burning nearby. Something big.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> You may have just wandered into a gunfight about to happen.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> You notice what apppears to be a mugging or shakedown in progress.</li>',
];
