const arrivalEvents = [
	'<li><span class="local-event-destiny-required">ATTENTION, CAPTAIN:</span> Imperial Starbase and/or Fleet nearby.</li>',
	'<li><span class="local-event-destiny-required">ATTENTION, CAPTAIN:</span> Imperial Customs is active in the area.</li>',
	'<li><span class="local-event-destiny-required">ATTENTION, CAPTAIN:</span> Fugitives being sought by Imperial Procurator and/or IOCI forces in the area.</li>',
	'<li><span class="local-event-destiny-required">ATTENTION, CAPTAIN:</span> Bureau of Ships & Services (BoSS) has a checkpoint nearby. You may be asked for your BoSS Datapad.</li>',
	'<li><span class="local-event-destiny-required">A DISTURBANCE IN THE FORCE:</span> All PCs gain 1 Force Die while in the system, but only <span style="background-color:black;color:red">Dark Side</span> pips <span class="font-normal starwars-dice force">•</span> may be used for successes.</li>',
];

const localEmpireEvents = [
	'<li><span class="local-event-destiny-required">IMPERIAL PRESENCE:</span> Imperial fighters are being dispatched towards you.</li>',
	'<li><span class="local-event-destiny-required">IMPERIAL PRESENCE:</span> Imperial Customs inspection. Stop engines and prepare to be boarded.</li>',
	'<li><span class="local-event-destiny-required">IMPERIAL PRESENCE:</span> Fugitive checkpoint with Imperial Procurator and stormtroopers. Prepare to be scanned.</li>',
	'<li><span class="local-event-destiny-required">IMPERIAL PRESENCE:</span> Bureau of Ships & Services (BoSS) checkpoint. Please present your BoSS Datapad.</li>',
	'<li><span class="local-event-destiny-required">A DISTURBANCE IN THE FORCE:</span> All PCs gain 1 Force Die while in the system, but only <span style="background-color:black;color:red">Dark Side</span> pips <span class="font-normal starwars-dice force">•</span> may be used for successes.</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Stealth check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Streetwise check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Computers check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Education check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Education check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Streetwise check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Core Worlds check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Core Worlds check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Underworld check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Computers check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Core Worlds check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Underworld check(s).</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> +<span class="font-normal starwars-dice boost">b</span> to Computers check(s).</li>',
	'<li><span class="local-event-free">SURPLUS:</span> +1 Rarity on weapons.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> +1 Rarity on armor.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> +1 Rarity on ship components.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> +1 Rarity on cybernetics.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on weapons.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on armor.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on ship components.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on cybernetics.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Maintenance crew at work in the area.</li>',
	'<li><span class="local-event-free">RUSH HOUR:</span> Vehicle/Foot traffic higher (+<span class="font-normal starwars-dice setback">s</span>) OR lower (+<span class="font-normal starwars-dice boost">b</span>) than normal.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Law enforcement has locked down an important location.</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Charm check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Coercion check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Computers check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Deception check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Mechanics check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Medicine check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Negotiation check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Streetwise check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Survival check(s).</li>',
	'<li><span class="local-event-destiny-optional">FAVORABLE CONTACTS:</span> +<span class="font-normal starwars-dice boost">b</span> to Vigilance check(s).</li>',
	'<li><span class="local-event-free">NEW SHERIFF:</span> Local leadership takes an interest in you.</li>',
	'<li><span class="local-event-free">SEE "EM COMING:</span> +<span class="font-normal starwars-dice boost">b</span> OR <span class="font-normal starwars-dice setback">s</span> to Piloting vs. spaceborne megafauna.</li>',
	'<li><span class="local-event-destiny-optional">LOOT ALERT:</span> Sensors indicate a debris field nearby.</li>',
	'<li><span class="local-event-destiny-optional">LOOT ALERT:</span> Sensors indicate a derelict spaceship nearby.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL EXPERT:</span> +<span class="font-normal starwars-dice boost">b</span> to Xenology regarding local flora and fauna.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on weapons.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on armor.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on survival gear.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on ship parts.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on riding beasts.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity on landspeeders.</li>',
	'<li><span class="local-event-free">FESTIVAL:</span> A local entertainment event draws crowds.</li>',
	'<li><span class="local-event-free">POLITICAL STRIFE:</span> Tensions are running high.</li>',
	'<li><span class="local-event-free">LOCAL WEATHER:</span> Sensors indicate a storm on the horizon.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> The local politician greets you at the landing site.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> You get the sensation you are being watched.</li>',
	'<li><span class="local-event-free">ATTENTION, SPACER:</span> You have an urgent message on GalactiMail.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Local prostitutes are very aggressive.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> <i>"You simply <em>have</em> to try the latest fad. Everyone\'s doing it!"</i></li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Mechanic.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Slicer.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Doctor.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Scout.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Core Worlds expert.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Education expert.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Lore expert.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Outer Rim expert.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Underworld expert.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Warfare expert.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Easy money (~10-100cr) to be made for a skilled Xenology expert.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> <i>"Psst! I got a <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Frangawl_Force_Powder" target="_blank">new kind of Spice</a> that will rock your world."</i> (+<span class="font-normal starwars-dice force">•</span><span class="font-normal starwars-dice force">•</span> next Force power; possible Conflict)</li>',
	'<li><span class="local-event-destiny-optional">AN OLD FRIEND:</span> My juvenile delinquent buddy is working for law enforcement now???</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> An antiquities dealer wishes to <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Category:Gear#RELICS" target="_blank">speak to you</a>. Come to the back door of the shop.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> A "political prisoner" desperately needs to get off world. They can pay.</li>',
	'<li><span class="local-event-free">IMPERIAL CHECKPOINT:</span> <i>"Move it along, citizen. Declare any contraband <em>before</em> you get to the scanner. Move it along."</i></li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A crowd gathers around a passionate speech being made.</li>',
	'<li><span class="local-event-free">IMPERIAL CHECKPOINT:</span> <i>"You there! Citizen, stop! Have you seen this droid?"</i></li>',
	'<li><span class="local-event-free">IMPERIAL CHECKPOINT:</span> <i>"Keep moving, citizen. Nothing to see here."</i></li>',
	'<li><span class="local-event-free">IMPERIAL CHECKPOINT:</span> <i>"Papers, please."</i></li>',
	'<li><span class="local-event-free">IMPERIAL CHECKPOINT:</span> <i>"No weapons allowed within one klik of the Senator. Please discard all weapons in the bin."</i></li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A celebrity and their entourage draws attention.</li>',
	'<li><span class="local-event-free">IMPERIAL CHECKPOINT:</span> A squad of stormtroopers scans the crowd for something specific.</li>',
	'<li><span class="local-event-free">KEEP FLYING:</span> <i>"This shipment needs to get there <em>yesterday</em>. Think you\'re fast enough?"</i></li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Election Day! Long lines clog the streets near voting locations.</li>',
	'<li><span class="local-event-free">WEATHER:</span> It\'s raining. <em>Hard.</em></li>',
	'<li><span class="local-event-free">IMPERIAL PRESENCE:</span> A squad of stormtroopers is temporarily camped near your ship. They pay no attention to you, but they can see your comings and goings.</li>',
	'<li><span class="local-event-free">IT FLOWS THROUGH ALL:</span> Gain 1 Force die on next Mechanics check.</li>',
	'<li><span class="local-event-free">IT FLOWS THROUGH ALL:</span> Gain 1 Force die on next Computers check.</li>',
	'<li><span class="local-event-free">IT FLOWS THROUGH ALL:</span> Gain 1 Force die on next Medicine check.</li>',
	'<li><span class="local-event-free">IT FLOWS THROUGH ALL:</span> Gain 1 Force die on next Survival check.</li>',
	'<li><span class="local-event-free">IT FLOWS THROUGH ALL:</span> Gain 1 Force die on next Core Worlds check.</li>',
	'<li><span class="local-event-free">IT FLOWS THROUGH ALL:</span> Gain 1 Force die on next Education check.</li>',
	'<li><span class="local-event-free">IT FLOWS THROUGH ALL:</span> Gain 1 Force die on next Lore check.</li>',
	'<li><span class="local-event-free">IT FLOWS THROUGH ALL:</span> Gain 1 Force die on next Outer Rim check.</li>',
	'<li><span class="local-event-free">IT FLOWS THROUGH ALL:</span> Gain 1 Force die on next Underworld check.</li>',
	'<li><span class="local-event-free">IT FLOWS THROUGH ALL:</span> Gain 1 Force die on next Warfare check.</li>',
	'<li><span class="local-event-free">IT FLOWS THROUGH ALL:</span> Gain 1 Force die on next Xenology check.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> The local <a href="https://starwars.fandom.com/wiki/Stim_tea" target="_blank">Stim tea</a> is very strong. (-<span class="font-normal starwars-dice setback">s</span> next Vigilance/Resilience check; withdrawal +<span class="font-normal starwars-dice setback">s</span> all checks, 4 hours)</li>',
	'<li><span class="local-event-destiny-optional">IMPERIAL CORRUPTION:</span> A uniformed officer has some <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Questioner-9_Interrogation_Serum" target="_blank">truth serum</a>." (Upgrade <span class="font-normal starwars-dice challenge">Difficulty</span> all checks to withhold information, 24 hours)</li>',
	'<li><span class="local-event-destiny-optional">IMPERIAL CORRUPTION:</span> A uniformed officer has some Corellian Whiskey that "fell off the delivery skiff".</li>',
	'<li><span class="local-event-destiny-optional">IMPERIAL CORRUPTION:</span> A uniformed officer has some Whyren\'s Reserve that "fell off the delivery skiff".</li>',
	'<li><span class="local-event-destiny-optional">IMPERIAL CORRUPTION:</span> A uniformed officer has some surplus Empire-branded <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Vutalamine" target="_blank">Vutalamine</a>. (<span class="font-normal starwars-dice proficiency">Upgrade</span> all checks to resist Stress or Fear; Downgrade <span class="font-normal starwars-dice downgrade-difficulty">Difficulty</span> of Ranged Light & Ranged Heavy at Extreme range, 24 hours; possible long term effects, +<span class="font-normal starwars-dice setback">s</span> all Intellect/Cunning, permanent)</li>',
	'<li><span class="local-event-destiny-optional">IMPERIAL CORRUPTION:</span> A uniformed officer has some surplus Empire-branded <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Affide_Crystal" target="_blank">"last resort" pills</a>. (Restricted poison, Rarity 8)</li>',
	'<li><span class="local-event-destiny-optional">IMPERIAL CORRUPTION:</span> A uniformed officer has some surplus Empire-branded <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Skirtopanol" target="_blank">Skirtopanol</a>. (CorSec Restricted truth serum, Rarity 8)</li>',
	'<li><span class="local-event-destiny-optional">IMPERIAL CORRUPTION:</span> A medical professional has some surplus Empire-branded <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Synthetic_Neuroparalytic" target="_blank">Dontmovatall medicine</a>. (injected Restricted neuroparalytic, Rarity 6)</li>',
	'<li><span class="local-event-destiny-optional">IMPERIAL CORRUPTION:</span> A medical professional has some surplus Empire-branded <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Synthetic_Neurotoxin" target="_blank">Dontuzatome medicine</a>. (injected/ingested/airborne Restricted neurotoxin, Rarity 6)</li>',
	'<li><span class="local-event-destiny-optional">IMPERIAL CORRUPTION:</span> A medical professional in bloodstained scrubs can hook you up with Restricted <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Category:Cybernetics target="_blank"" target="_blank">cybernetic gear</a>. <strong>For a price.</strong> (Restricted gear, Rarity 3-8)</li>',
	'<li><span class="local-event-destiny-optional">IMPERIAL CORRUPTION:</span> A civilian Imperial employee has a lead on an Empire warehouse containing Restricted <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Category:Infiltration target="_blank"" target="_blank">infiltration gear</a>. (Restricted gear, Rarity 3-9)</li>',
	'<li><span class="local-event-destiny-optional">IMPERIAL CORRUPTION:</span> An off-duty police officer has some surplus Empire-branded <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Category:Security" target="_blank">prison gear</a>. (Restricted gear, Rarity 5-8)</li>',
	'<li><span class="local-event-destiny-optional">IMPERIAL CORRUPTION:</span> A grease-stained civilian Imperial mechanic has some surplus Empire-branded <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Category:Tools" target="_blank">tools</a>. (Restricted gear, Rarity 5-9)</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A holo-journalist and her technician want to broadcast a story about your heroic exploits.</li>',
	'<li><span class="local-event-destiny-required">SCRATCH THE PAINT:</span> Your ship is buffeted by some sort of impact and takes one Critical Hit.</li>',
	'<li><span class="local-event-free">YOUR MOM CALLED:</span> Would it kill you to holo-call once in a while? +<span class="font-normal starwars-dice boost">b</span> to next Coercion check.</li>',
	'<li><span class="local-event-destiny-optional">A BRUSH WITH GREATNESS:</span> You run into a local celebrity and hit it off. +<span class="font-normal starwars-dice boost">b</span> to all Leadership checks.</li>',
	'<li><span class="local-event-free">SURPLUS:</span> -1 Rarity, +<span class="font-normal starwars-dice boost">b</span> on weapon modifications.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity, +<span class="font-normal starwars-dice setback">s</span> on weapon modifications.</li>',
	'<li><span class="local-event-destiny-optional">I KNOW A GUY:</span> Not a "fence". Not a "trafficker". They are an "antiquities dealer" who "specializes in hard to find collectibles". (+1 Rarity to sell <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Category:Gear#RELICS" target="_blank">Relics</a>, and handles (R)estricted items under the table.)</li>',
	'<li><span class="local-event-free">PROBABLY NOT A TRAP:</span> You hear a muffled cry for help from a dark alley.</li>',
	'<li><span class="local-event-free">IMPERIAL PRESENCE:</span> <i>"Watch out, the Imps are running undercover operations. Trust no one."</i></li>',
	'<li><span class="local-event-free">ATTENTION, NAVIGATOR:</span> Real-space debris detected at your preferred destination. (automatic +<span class="font-normal starwars-dice threat">Threat</span> to Astrogation).</li>',
	'<li><span class="local-event-free">ATTENTION, NAVIGATOR:</span> Minor traffic jam at destination. (automatic +<span class="font-normal starwars-dice threat">Threat</span> to Astrogation).</li>',
	'<li><span class="local-event-free">ATTENTION, NAVIGATOR:</span> Major traffic jam at destination. (automatic +<span class="font-normal starwars-dice threat">Threat</span><span class="font-normal starwars-dice threat">Threat</span> to Astrogation).</li>',
	'<li><span class="local-event-free">ATTENTION, NAVIGATOR:</span> You recognize a familiar hyperspace route. (+<span class="font-normal starwars-dice boost">b</span> to Astrogation).</li>',
	'<li><span class="local-event-destiny-required">ATTENTION, NAVIGATOR:</span> Hyperspace anomaly buffets the ship. (+1 System Strain)</li>',
	'<li><span class="local-event-destiny-required">ATTENTION, NAVIGATOR:</span> Undetected hyperspace debris impacted the ship. (+1 Hull Trauma)</li>',
	'<li><span class="local-event-destiny-required">ATTENTION, NAVIGATOR:</span> Hyperdrive failure in flight. Dead stop, position unknown.</li>',
];

const localOldWestEvents = [
	'<li><span class="local-event-free">ATTENTION, CAPTAIN:</span> Potential megafauna in the area.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on weapons.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on armor.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on survival gear.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on ship parts.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on riding beasts.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> +1 Rarity on landspeeders.</li>',
	'<li><span class="local-event-free">SHORTAGE:</span> The starport is experiencing an outage of some important service.</li>',
	'<li><span class="local-event-destiny-optional">ATTENTION, SPACER:</span> You run into an old friend. Do you think they have forgiven you yet?</li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> People are desperate for starship parts and will try to steal them off your ship.</li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> Pickpockets have been reported in the area recently.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> Due to recent circumstances, all nonsapient droids MUST have a restraining bolt.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> Due to recent circumstances, droids are considered unwelcome in some establishments.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> Due to recent circumstances, cybernetics are considered unwelcome in some establishments.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Adorable local urchins mob you for credits and candy. But they see <em>everything</em>.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Due to recent events, droids are considered mildly popular.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Due to recent events, cybernetics are considered mildly popular.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A small domesticated creature takes a liking to you.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> The sky is full of (meteors, strange clouds, flying creatures, ...)</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> A fresh bloodstain is visible on the ground near your ship.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> You are cordially invited to a gambling event.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> <em><b>Wanted:</b></em> Fearless PodRacer Jockeys and mechanics for the local podraces.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> <i>"Say, that\'s a shiny ship you got there. Is she for sale?"</i></li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> <i>"How much you want for that droid?"</i></li>',
	'<li><span class="local-event-free">ATTENTION, PILOT:</span> A local hotshot challenges you to a race.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A merchant requests your assistance with a local thief.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A thief requests your assistance with a local merchant.</li>',
	'<li><span class="local-event-destiny-optional">ATTENTION, CAPTAIN:</span> Sensors indicate a possible hideout in this system (+<span class="font-normal starwars-dice setback">s</span> to be detected).</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Everyone seems to be looking at you curiously.</li>',
	'<li><span class="local-event-free">ATTENTION, CAPTAIN:</span> Small animal detected clinging to the hull. Is it friendly or hungry?</li>',
	'<li><span class="local-event-free">FESTIVAL:</span> A food festival promises large crowds.</li>',
	'<li><span class="local-event-free">NEW TAXES:</span> Spaceport fees halved/doubled.</li>',
	'<li><span class="local-event-free">ATTENTION, GUNNER:</span> A local wealthy scion challenges you to a duel. Do you want to "make it interesting"?</li>',
	'<li><span class="local-event-free">ATTENTION, DIPLOMAT:</span> An impoverished and troddendown local family needs your help with local law enforcement.</li>',
	'<li><span class="local-event-free">ATTENTION, DIPLOMAT:</span> Local law enforcement needs your help apprehending a brutal local crime family.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Did you hear something in the cargo hold?</li>',
	'<li><span class="local-event-free">ATTENTION, MECHANIC:</span> You find a stowaway hiding in the engine room.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Rumors abound of an insane old wizard living in the hills.</li>',
	'<li><span class="local-event-destiny-optional">ATTENTION, SLICER:</span> With a little "creative recordkeeping", starport fees might be "waived".</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Swoop bike races promise easy money (~10-100cr) for talented drivers and gamblers.</li>',
	'<li><span class="local-event-destiny-optional">AN OLD FRIEND:</span> Hey, my buddy works at the starport! They are a talented...(+<span class="font-normal starwars-dice boost">b</span> to one chosen skill)</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> You witness a local crime. The perp got away but you know where they are.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> You come across blackmail material against a local politician.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Fuel Shortage. <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Category:Riding" target="_blank">Riding beasts</a> are the way to go until something is done.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> Local farm/shop requests your assistance with a brutal gang.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> Local "militia" requests your assistance collecting "protection fees".</li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> <i>"My friend says he doesn\'t like you. <em>I</em> don\'t like you either."</i></li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> <i>"Hey! You can\'t bring that thing in here!"</i></li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> <i>"Check yer weapons at the door. We\'ve had trouble recently."</i></li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> Scorch marks on (another ship, the starport, a local business, ...)</li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> <i>"My friend says you owe him 200 credits. He says I get half."</i></li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> Something is burning nearby. Something big.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> You may have just wandered into a gunfight about to happen.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> You notice what appears to be a mugging or shakedown in progress.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> A farm family requests your help with a predator.</li>',
	'<li><span class="local-event-free">LOOT ALERT:</span> A local knows where a smuggler\'s cache is hidden. They need your help to steal it.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> Blackouts occur randomly as the local power generator is unstable.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> Every door is locked and nobody will come out.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> A battered, sparking droid lies out of the way of traffic. It has one final message before it dies.</li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> You find a datapad or credstick you think you could steal easily.</li>',
	'<li><span class="local-event-free">THE HERO OF:</span> You are mistaken for a local hero. Free drinks as long as you can keep up the ruse.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A local urchin claims to be a Jedi and wants to be your padawan.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A local farm needs to get their space-cows to market. Time is running out!</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A local farm needs help recovering their stolen space-cows.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A rural community needs help with bandits stealing their (land, water, mine, ...)</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A local Harvest Festival has everyone wearing colorful costumes.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A valuable train shipment is going lightly defended. Will you help it reach its destination?</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A valuable train shipment is going lightly defended. It almost looks too easy.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Colonists need to relocate to a new location, wagons and space-cows and all.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> Feuding families request your assistance in keeping a wedding between them safe.</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A local needs help escaping an arranged marriage.</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> Local rodeo needs contestants. Valuable prizes!</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A regional politician requests your assistance delivering medicine to a remote village.</li>',
	'<li><span class="local-event-destiny-required">IMPERIAL BLOCKADE:</span> Nobody gets in or out until the situation is resolved.</li>',
	'<li><span class="local-event-destiny-required">PIRATES:</span> <i>"Prepared to be boarded. Your cargo or your life."</i> Roll initiative for space combat.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> <i>"Wanna buy some Death Sticks?"</i></li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> The locally brewed cocktail makes you smart (+<span class="font-normal starwars-dice boost">b</span> Cunning) but clumsy (+<span class="font-normal starwars-dice setback">s</span> Agility).</li>',
	'<li><span class="local-event-destiny-required">WEATHER:</span> Extreme weather (violent storm, drought, frigid, broiling, quakes, volcanic eruption, ...).</li>',
	'<li><span class="local-event-free">SCUM & VILLAINY:</span> You bear a resemblance to a wanted fugitive.</li>',
	'<li><span class="local-event-destiny-required">WRETCHED HIVE:</span> Paranoia abounds (+<span class="font-normal starwars-dice setback">s</span> to all social skills)</li>',
	'<li><span class="local-event-destiny-required">SHORTAGE:</span> No spare parts (+<span class="font-normal starwars-dice setback">s</span> to Mechanics)</li>',
	'<li><span class="local-event-destiny-required">SCUM & VILLAINY:</span> Security lockdown (+<span class="font-normal starwars-dice setback">s</span> to Slicing)</li>',
	'<li><span class="local-event-destiny-required">WRETCHED HIVE:</span> Police lockdown (+<span class="font-normal starwars-dice setback">s</span> to Skulduggery)</li>',
	'<li><span class="local-event-destiny-required">WEATHER:</span> Low visibility (+<span class="font-normal starwars-dice setback">s</span> to Perception & Piloting outdoors)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some fresh <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Avabush_Spice" target="_blank">Avabush</a>."</i> (recover 1 Strain; lethargy, limit 1 <span class="font-normal starwars-dice proficiency">Upgrade</span> per check, one encounter; Upgrade <span class="font-normal starwars-dice challenge">Difficulty</span> to conceal the truth, one encounter).</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some nice <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Booster_Blue" target="_blank">Booster Blue</a> for you."</i> (<span class="font-normal starwars-dice proficiency">Upgrade</span> Agility/Intellect/Cunning once; cannot recover Strain this session).</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some sweet <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Death_Sticks" target="_blank">Death Sticks</a>."</i> (<span class="font-normal starwars-dice proficiency">Upgrade</span> Charm/Cool/Resilience once; +<span class="font-normal starwars-dice setback">s</span> all tasks, one encounter)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some kickin\' <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Glitterstim" target="_blank">Glitterstim</a>."</i> (+<span class="font-normal starwars-dice boost">b</span><span class="font-normal starwars-dice boost">b</span><span class="font-normal starwars-dice boost">b</span> all Perception & Vigilance, one encounter; highly addictive; possible temporary telepathy)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some rockin\' <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Lesai" target="_blank">Lesai</a>."</i> (space methamphetamine; recover Strain without sleep; withdrawal after 24 hours nonuse; possible temporary psychosis)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some primo <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Yarrock" target="_blank">Yarrock</a>."</i> (immune to Fear, one encounter; +<span class="font-normal starwars-dice setback">s</span> all Willpower & Presence, this session)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some fresh <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Gunjack_Spice" target="_blank">Gunjack</a>."</i> (Brawn +1, one encounter; upgrade <span class="font-normal starwars-dice challenge">Difficulty</span> all Agility/Intellect/Cunning, this session)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some tight <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Impact" target="_blank">Impact</a> right here."</i> (<span class="font-normal starwars-dice proficiency">Upgrade</span> all Agility, one encounter; withdrawal +<span class="font-normal starwars-dice setback">s</span> all Agility/Cunning/Intellect, this session)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some pure <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Ji_Rikknit" target="_blank">Ji Rikknit</a> right here."</i> (recover 1 Strain; Easy <span class="font-normal starwars-dice difficulty">p</span> per dose Resilience to avoid 1 Obligation [addiction])</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some fresh <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Karrak_Spice" target="_blank">Karrack</a>."</i> (-<span class="font-normal starwars-dice setback">s</span><span class="font-normal starwars-dice setback">s</span><span class="font-normal starwars-dice setback">s</span> from pain or illness, 12 hours; +<span class="font-normal starwars-dice threat">Threat</span> all checks, 24 hours; Force users double duration, Force rating -1 while affected)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some nice <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Longsight" target="_blank">Longsight</a>."</i> (Willpower +1, one encounter; +2 Strain at start of turn, while affected)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some sweet <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Marcan_Herb" target="_blank">Marcan Herb</a>."</i> (mild euphoria; +<span class="font-normal starwars-dice boost">b</span> next Perception check; +<span class="font-normal starwars-dice setback">s</span> Discipline & Vigilance, one encounter)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some kickin\' <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Muon_Gold" target="_blank">Muon Gold</a>."</i> (+<span class="font-normal starwars-dice boost">b</span> all Cunning & Presence checks, one encounter; possible +<span class="font-normal starwars-dice setback">s</span> all Intellect & Cunning, one encounter)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some rockin\' <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Nannarium_Root" target="_blank">Nannarium Root</a>."</i> (<span class="font-normal starwars-dice proficiency">Upgrade</span> one Intelligence/Cunning check; +2 Strain)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some primo <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Neutron_Pixie" target="_blank">Neutron Pixie</a>."</i> (+<span class="font-normal starwars-dice advantage">Advantage</span><span class="font-normal starwars-dice advantage">Advantage</span> all Agility & Willpower checks, one encounter; withdrawal +<span class="font-normal starwars-dice threat">Threat</span> all Brawn & Intellect & Cunning checks, this session)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some tight <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Ryll" target="_blank">Ryll</a> just for you."</i> (ignore Critical Injury temporarily, one encounter; withdrawal, suffer Critical Injury effects, +<span class="font-normal starwars-dice setback">s</span><span class="font-normal starwars-dice setback">s</span>, this session)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some new <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Yaladai_Spice" target="_blank">Yaladai</a>."</i> (gain 3 Soak for involuntary Strain taken, one encounter; Force users +<span class="font-normal starwars-dice force">Force</span> all Force powers, but Strain and Conflict doubled for <span class="font-normal starwars-dice force">•</span> used; highly addictive)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some bespoke <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Ashes_of_Malachor" target="_blank">Ashes of Malachor</a>."</i> (Force-sensitive only; +5 Conflict, +<span class="font-normal starwars-dice success">success</span><span class="font-normal starwars-dice threat">Threat</span> all attacks, one encounter)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some heady <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Frangawl_Force_Powder" target="_blank">Frangawl Force Powder</a>."</i> (Force-sensitive only; +10 Conflict, +<span class="font-normal starwars-dice force">•</span><span class="font-normal starwars-dice force">•</span> next Force power check)</li>',
	'<li><span class="local-event-destiny-optional">LOCAL COLOR:</span> The local <a href="https://starwars.fandom.com/wiki/Stimcaf" target="_blank">Stimcaf</a> is even thicker than normal. (-<span class="font-normal starwars-dice setback">s</span> next Vigilance/Resilience check; withdrawal +<span class="font-normal starwars-dice setback">s</span>, 4 hours)</li>',
	'<li><span class="local-event-destiny-optional">SCUM & VILLAINY:</span> A shady character has some "<a href="https://star-wars-rpg-ffg.fandom.com/wiki/Dendriton_Toxin" target="_blank">Vengeance Juice</a>". (cruel Restricted poison, Rarity 7)</li>',
	'<li><span class="local-event-destiny-optional">SCUM & VILLAINY:</span> A shady character has some clearly stolen Empire-branded "<a href="https://star-wars-rpg-ffg.fandom.com/wiki/Dioxis_Gas" target="_blank">Coward\'s Solution</a>". (airborne Restricted poison, Rarity 6)</li>',
	'<li><span class="local-event-destiny-optional">SCUM & VILLAINY:</span> A shady character has some freshly harvested <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Raquor_Venom" target="_blank">Raquor\'s Kiss</a>. (injected/airborne Restricted poison, Rarity 7)</li>',
	'<li><span class="local-event-destiny-optional">YOUR DEALER CALLED:</span> <i>"Psst! I got some <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Bubse_Spice" target="_blank">Bubse</a>."</i> (Wound Threshold +4, one encounter; +20 Critical Hit result, one encounter)</li>',
	'<li><span class="local-event-destiny-optional">SCUM & VILLAINY:</span> A shady character has some <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Category:Electronics" target="_blank">gadgets</a> you might be interested in. (Restricted electronics, Rarity 5-9)</li>',
	'<li><span class="local-event-destiny-optional">WRETCHED HIVE:</span> <i>"Hey, you looking for <a href="https://star-wars-rpg-ffg.fandom.com/wiki/Category:Recreation" target="_blank">an edge at cubes or cards</a>?"</i> (Restricted gear, Rarity 5-6)</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A ragtag group of children claim to have found a derelict spaceship. They want to trade for its location.</li>',
	'<li><span class="local-event-destiny-required">IMPERIAL PRESENCE:</span> An Imperial Star Destroyer lurks menacingly above the city. (+<span class="font-normal starwars-dice setback">s</span> all Skulduggery/Streetwise checks)</li>',
	'<li><span class="local-event-free">LOCAL COLOR:</span> A confused-looking trio of humans in yellow, blue, and red uniform shirts ask if you can help them "beam up". Whatever that means.</li>',
	'<li><span class="local-event-destiny-required">WEATHER:</span> Heat wave/Cold front (+<span class="font-normal starwars-dice setback">s</span> all Athletics/Coordination/Resilience/Survival/Brawl/Melee/Lightsaber checks).</li>',
	'<li><span class="local-event-destiny-required">A RUDE WELCOME:</span> Your ship is hit by something and takes one Critical Hit during final landing approach.</li>',
	'<li><span class="local-event-free">LOCAL EXPERTS:</span> -1 Rarity, +<span class="font-normal starwars-dice boost">b</span> on weapon modifications.</li>',
	'<li><span class="local-event-free">WE DON\'T DO THAT HERE:</span> +1 Rarity, +<span class="font-normal starwars-dice setback">s</span> on weapon modifications.</li>',
	'<li><span class="local-event-free">WRETCHED HIVE:</span> An angry mob with torches and pitchforks awaits you as you return to the ship.</li>',
	'<li><span class="local-event-destiny-required">WHO SHOT FIRST?:</span> Roll Initiative.</li>',
	'<li><span class="local-event-free">ATTENTION, CAPTAIN:</span> Distress call received. We appear to be the closest vessel. Your orders?</li>',
	'<li><span class="local-event-free">SPACE-LEOPARDS!:</span> They want to eat your face. Roll initiative.</li>',
	'<li><span class="local-event-free">ATTENTION, NAVIGATOR:</span> Real-space debris detected at your preferred destination. (automatic +<span class="font-normal starwars-dice threat">Threat</span> to Astrogation).</li>',
	'<li><span class="local-event-free">ATTENTION, NAVIGATOR:</span> Minor celestial event since last hyperspace charting. (automatic +<span class="font-normal starwars-dice threat">Threat</span> to Astrogation).</li>',
	'<li><span class="local-event-free">ATTENTION, NAVIGATOR:</span> Major celestial event since last hyperspace charting. (automatic +<span class="font-normal starwars-dice threat">Threat</span><span class="font-normal starwars-dice threat">Threat</span> to Astrogation).</li>',
	'<li><span class="local-event-free">ATTENTION, NAVIGATOR:</span> You recognize a familiar hyperspace route. (+<span class="font-normal starwars-dice boost">b</span> to Astrogation).</li>',
];

