const hyperspaceRoutes = [
{
	"Name": "Corellian Run",
	"SpeedFactor": 0.5,
	"Route": "Coruscant,Ixtlar,Wukkar,Kailor V,Xorth,Vuma,Leria Kerlsil,Perma,Lolnar,Rehemsa,Sedratis,Rydonni Prime,Corellia,Nubia,Tinnel IV,Loronar,Byblos,Pencael IV,Havricus,Iseno,Denon,Spirana,Rhommamool,Tlactehon,Allanteen VI,Gamor,Milagro,Thaere Privo,New Cov,Doldur,Druckenwell,Kabray,Algara II,Andosha II,Mon Gazza,Herdessa,Radnor,Christophsis,Arkanis,Sirpar,Gorno,Dalchon,Ryloth,Wrea",
	"Junctions": "Perlemian Trade Route,Namadii Corridor,Metellos Trade Route,Corellian Trade Spine,Hydian Way,Gamor Run,Harrin Trade Corridor,Duros Space Run,Reena Trade Route,Llanic Spice Run,Triellus Trade Route,Corellian Skip Run,Death Wind Corridor,Old Corellian Run,Ryloth Road",
},
{
	"Name": "Rimma Trade Route",
	"SpeedFactor": 0.5,
	"Route": "Abregado-rae,Dentaal,Giju,Ghorman,Vanik,Thyferra,Tauber,Yag'Dhul,Sukkult,Wroona,Tregillis,Vandelhelm,Woostri,Daemen,Alakatha,Lanthe,Vondarc,Medth,Tshindral III,Sullust,Agomar,Eriadu,Clak'dor VII,Triton,Praesitlyn,Sluis Van,Bpfassh,Denab,Tarabba Prime,Adarlon,Karideph",
	"Junctions": "Shapani Bypass,Giju Run,Corellian Trade Spine,Harrin Trade Corridor,Enarc Run,Ado Spine,Hydian Way,Senex Trace,Nothoiin Corridor,Lipsec Run,Sharlissian Trade Corridor,Coyn Route,Trition Trade Route",
},
{
	"Name": "Perlemian Trade Route",
	"SpeedFactor": 0.5,
	"Route": "Coruscant,Alsakan,Grizmallt,Anaxes,Corulag,Chandrila,Brentaal IV,Esseles,Rhinnal,Ralltiir,Delle system,Yabol Opa,Ifmix VI,Shulstine V,Castell,Raithal,Vurdon Ka,Joiol,Chazwa,Relatta,Tirahnn,Dalcretti,Taanab,Sermeria,Carcel,Pirin,Gizer,Lantillies,Rearqu Cluster,Jeyell,Roche,Orleon,Talcene,Salvara system,Euceron,Abhean,The Wheel,Centares,Antemeridias,Budpock,Columex,Arcan IV,Lianna,Barseg,Lorrad,Desevro,Kanaver,Janodral Mizar,Ank Ki'Shor,Estaria,Makem Te,Quermia",
	"Junctions": "Corellian Run,Metellos Trade Route,Namadii Corridor,Koros Trunk Line,Hydian Way,Commenor Run,Vaathkree Trade Corridor,Randon Run,Triellus Trade Route,Salin Corridor,Shaltin Tunnels,Tion Trade Route,Overic Griplink",
},
{
	"Name": "Hydian Way",
	"SpeedFactor": 0.5,
	"Route": "Bonadan,D'ian,Lythos I,Lythos VI-IX,Lythos XIV,Mall'ordian,Reltooine,Cadomai Prime,Ruuria,Listehol,Tantive IV,Doniphon,Telos IV,Shi'kar Straits,Praadost II,Pho Ph'eah,Serenno,Toprawa,Simpla-12,Hynah,Sorrus,Feriae Junction,Tierell,Celanon,Hijado,Botajef,Harloen,Bandomeer,Taris,Skorrupon,Corsin,Leafar,Chennis,Adin,Draria,Viga,Kidriff 5,Nessem,Bogden,Paqualis III,Per Lupelo,Drearia,Champala,Nierport VII,Uviuy Exen,Wakeelmui,Brentaal IV,Skako,Aldraig IV,Demophon,Glithnos,Fedalle,Talravin,Ruul,Trellen,Mawan,Loretto,Baraboo,Bellassa,Jaciprus,Voktunma,Exodeen,Boudolayz,Herzob,Besnia,Koensayr,Aquilae,Denon,Sagar,Ronyards,Chardaan,Babbadod,Nordra,Perithal VI,Shibric,Baroli,Gacerian,Ragith III,Majoor,Ramordia,Arrgaw,Plagen,ZeHeth,Malastare,Chryya,Aquilaris Minor,Kamasto,Ventruun,Oranessan,Darkknell,Scelepas,Cmaoli Di,Eriadu,Averam,Rogue Antar,Shumavar,Atravis,Tosste,Rutan,Fwatna,Terminus,Imynusoph",
	"Junctions": "Tingel Route,Solenbaran Merchant Route,Shaltin Tunnels,Trianii Shunt,Authority Guardian Corridor,Intra-Sector Spur,Listehol Run,Junction-Tierell Loop,Thesme Trace,Celanon Spur,Salin Corridor,Braxant Run,Vaathkree Trade Corridor,Shwuy Exchange,Perlemian Trade Route,Commenor Run,Trellen Trade Route,Quellor Run,Corellian Run,Shipwrights' Trace,Harrin Trade Corridor,Enarc Run,Duros Space Run,Rimma Trade Route,Nothoiin Corridor,Lipsec Run,Corellian Trade Spine",
},
{
	"Name": "Corellian Trade Spine",
	"SpeedFactor": 0.5,
	"Route": "Corellia,Duro,Chasin,Condular,Gandeal,Belazura,Bryexx,Enisca,Kelada,Foless,Bestine IV,Mechis,Renillis,Yag'Dhul,Harrin,Moorja,Calus,Epica,Roona,Borkyne,Kinyen,Pendari,Tar Morden,Calonica,Bomis Koori IV,Kriselist,Chibias,Kaal,Dalisor,Jiroch-Reslia,Quamar,Mugaar,Javin,Aztubek,Kumru,High Chunah,Kirtarkin,Mexeluine,Gerrenthum,Indellian,Bendeluum,Zhanox,Ione,Mataou,Anantapar,Shuxl system,Ertegas,Darlyn Boda,Orn Kios,Ozu,Isde Naha,Togominda,Berrol's Donn,Sil'Lume,Manpha,Terminus",
	"Junctions": "Corellian Run,Duros Space Run,Shipwrights' Trace,Rimma Trade Route,Harrin Trade Corridor,Great Gran Run,D'Aelgoth Trade Route,Nothoiin Corridor,Koda Spur,Ison Corridor,Lipsec Run,Hydian Way",
},
{
	"Name": "Triellus Trade Route",
	"SpeedFactor": 0.9,
	"Route": "Centares,Sy Myrth,Handooine,Jabiim,Taskeed,Dennogra,Junkfort,Nimat,Tammar,Kegan,Gestrex III,Norval II,Kubindi,Drualkiin,Formos,Bheriz,Aduba-3,Glottal,Teth,Rampa 1,Dilbana,Clantaano III,Barab III,Dubrava,Syvris,Arami,Gamorr,Lyran IV,Arvina,Molavar,Nurasenti,Koiogra,Piroket,A-Foroon,B-Foroon,C-Foroon,Ooo-temiuk,Tatooine,Andooweel,Kemal,New Ator,Issor,Arkanis,Nelvaan,Tythe,Llanic,Zhar,Farstine,Ryndellia,Enarc",
	"Junctions": "Perlemian Trade Route,Salin Corridor,Lesser Lantillian Route,Kessel Run,Pabol Sleheyron,Shag Pabol,Hollastin Run,The Sy-Y,Manda Merchant Route,5709-DC Shipping Lane,Corellian Skip Run,The Crystal Passage,Old Corellian Run,Tatooine Dash,Najiba Loop,Corellian Run,Llanic Spice Run,Five Veils Route,Duros Space Run,Enarc Run",
},
{
	"Name": "Corellian Skip Run",
	"SpeedFactor": 0.9,
	"Route": "Ryloth,Tatooine",
	"Junctions": "Corellian Run,Death Wind Corridor,Old Corellian Run,Ryloth Road,The Crystal Passage,Old Corellian Run,Tatooine Dash,Triellus Trade Route",
},
{
	"Name": "Kessel Run",
	"SpeedFactor": 0.9,
	"Route": "Formas,Rion,Kessel",
	"Junctions": "Kessel Trade Corridor,Pabol Sleheyron,Triellus Trade Route",
},
{
	"Name": "Kessel Trade Corridor",
	"SpeedFactor": 0.9,
	"Route": "Kessel,Zerm",
	"Junctions": "Pabol Sleheyron,Kessel Run",
},
{
	"Name": "Namadii Corridor",
	"SpeedFactor": 0.9,
	"Route": "Coruscant,Tanjay IV,Weerden,Galvoni III,Twith,Pantolomin,Borleias,Ord Mirit,Palanhi,Carratos,Voltare,Meastrinnar,Aphran,Bengat,Bilbringi,Rondai-2,Coth Fuuras space station,Dorin,Carvandir,Vaced,Glee Anselm,Belshar Othacuu,Ord Varee,Kalaan,Masgen,Ansion,Namadii",
	"Junctions": "Perlemian Trade Route,Metellos Trade Route,Corellian Run,Hyabb-Twith Corridor,Shwuy Exchange,Celanon Spur,Rago Run",
},
{
	"Name": "Metellos Trade Route",
	"SpeedFactor": 0.9,
	"Route": "Coruscant,Metellos,Norkronia,Alland,Cal-Seti,Galantos,Orooturoo",
	"Junctions": "Perlemian Trade Route,Corellian Run,Koros Trunk Line,Namadii Corridor,Metellos–Ilum hyperlane,Ag Circuit,Widek Bypass ",
},
{
	"Name": "Gamor Run",
	"SpeedFactor": 0.9,
	"Route": "Gamor,Merkat,Aridus,Charra,Aikhibba,Hoylin,Beris,Deneba,Chokan,Shador,Thokosia,Daalang,Circumtore,Rorak 4,Rorak 5",
	"Junctions": "Corellian Run,Harrin Trade Corridor,Trax Tube,Bothan Run,Kaaga Run,Hollastin Run,Shag Pabol",
},
{
	"Name": "Harrin Trade Corridor",
	"SpeedFactor": 0.9,
	"Route": "Harrin,Wroona,Droecil,Lohopa II,Jurzan,Arrgaw,Lazerian IV,Ruten,Brevost,Momansi Belt,Krann,Coonee,Sika,Milagro,Merren",
	"Junctions": "Corellian Trade Spine,Rimma Trade Route,Hydian Way,Kira Run,Corellian Run",
},
{
	"Name": "Duros Space Run",
	"SpeedFactor": 0.9,
	"Route": "Churba,New Cov,Kalarba,Glom Tho,Triffis,Bannistar Station,Enarc,Alui,Verdanth,Aplooine,Sanrafsix,Heptooine,Jutrand,Darkknell",
	"Junctions": "Corellian Run,Enarc Run,Triellus Trade Route,Sanrafsix Corridor,Gevarno Loop,Hydian Way",
},
{
	"Name": "Reena Trade Route",
	"SpeedFactor": 0.9,
	"Route": "Druckenwell,Haseria,Monastery,Masterra,Nexus Ortai,Spirador,Bothawui",
	"Junctions": "Corellian Run,Bothan Run,Kaaga Run,Manda Merchant Route",
},
{
	"Name": "Llanic Spice Run",
	"SpeedFactor": 0.9,
	"Route": "Mon Gazza,Llanic,Magravia,Socorro,Bahalian,Andasala,Reuss,Jermac,Midani,Spice Terminus",
	"Junctions": "Corellian Run,Triellus Trade Route,Ryloth Road,Five Veils Route",
},
{
	"Name": "Death Wind Corridor",
	"SpeedFactor": 0.9,
	"Route": "Ryloth,Roon",
	"Junctions": "Corellian Run,Corellian Skip Run,Old Corellian Run,Ryloth Road,Manda-Roon Merchant Route",
},
{
	"Name": "Old Corellian Run",
	"SpeedFactor": 0.9,
	"Route": "Mon Gazza,Milarian,Pii,Austan,Utaruun,Tatooine,Obana,Vor Deo,Khubeaie,Shimia,Ryloth",
	"Junctions": "Corellian Run,Llanic Spice Run,Trans Gulf Route,Corellian Skip Run,The Crystal Passage,Tatooine Dash,Triellus Trade Route,Cranan-Excarga Route,Vaschean Way,Corellian Run,Corellian Skip Run,Death Wind Corridor,Ryloth Road",
},
{
	"Name": "Ryloth Road",
	"SpeedFactor": 0.9,
	"Route": "Ryloth,Socorro",
	"Junctions": "Corellian Run,Corellian Skip Run,Death Wind Corridor,Old Corellian Run,Llanic Spice Run",
},
{
	"Name": "Shapani Bypass",
	"SpeedFactor": 0.9,
	"Route": "Thyferra,Mrlsst,Lamuir IV,Tallaan,Aleron,Achillea,Vindalia,Diamal,Bith,Abregado-rae",
	"Junctions": "Rimma Trade Route,Procopian Shipping Lane,Giju Run",
},
{
	"Name": "Giju Run",
	"SpeedFactor": 0.9,
	"Route": "Tallaan,Giju,Omar,Illodia,Dahrtag,Hjaff,Atrisia",
	"Junctions": "Shapani Bypass,Procopian Shipping Lane,Rimma Trade Route",
},
{
	"Name": "Enarc Run",
	"SpeedFactor": 0.9,
	"Route": "Enarc,Naboo,Alassa Major,Kalinda,Nigel,Roldalna,Ropagi II,Plagen,Krann (Opiteihr),Vogel 7,Vondarc",
	"Junctions": "Triellus Trade Route,Duros Space Run,Kira Run,Hydian Way,Rimma Trade Route",
},
{
	"Name": "Ado Spine",
	"SpeedFactor": 0.9,
	"Route": "Medth,Indupar,StarForge Nebula,Eiattu 6,Ord Gimmel",
	"Junctions": "Rimma Trade Route,Senex Trace,Yankirk Route",
},
{
	"Name": "Senex Trace",
	"SpeedFactor": 0.9,
	"Route": "Karfeddion,Fengrine,Neelanon,Senex,Rindao,Parada,Ord Gimmel",
	"Junctions": "Anturi Reach,Senex-Juvex Loop,Ado Spine,Yankirk Route",
},
{
	"Name": "Nothoiin Corridor",
	"SpeedFactor": 0.9,
	"Route": "Gerrenthum,Council,Nothoiin,Saila Na,Bavva,Dolla,Eriadu",
	"Junctions": "Corellian Trade Spine,Lutrillian Cross,Nothoiin Route,Rimma Trade Route,Hydian Way (Eriadu Way),Lipsec Run,Yankirk Route",
},
{
	"Name": "Lipsec Run",
	"SpeedFactor": 0.9,
	"Route": "Lipsec,Virgillia,Sump,Keskin,Abridon,Isde Naha,Bettel,Mev,Kelrodo-Ai,Dorvalla,Eriadu",
	"Junctions": "Corellian Trade Spine,Nothoiin Route,Hydian Way (Eriadu Way),Nothoiin Corridor,Rimma Trade Route,Yankirk Route",
},
{
	"Name": "Sharlissian Trade Corridor",
	"SpeedFactor": 0.9,
	"Route": "Triton,Xagobah,Kabal,Nellac Kram,Sharlissia system",
	"Junctions": "Rimma Trade Route,Sanrafsix Corridor",
},
{
	"Name": "Coyn Route",
	"SpeedFactor": 0.9,
	"Route": "Coyn,Tantra",
	"Junctions": "Elrood-Derilyn Trade Route,Rimma Trade Route",
},
{
	"Name": "Trition Trade Route",
	"SpeedFactor": 0.9,
	"Route": "Karideph,Pergitor,Kal'Shebbol,Torize,Kolatill,Charis,Gandle Ott",
	"Junctions": "Rimma Trade Route,",
},
{
	"Name": "Koros Trunk Line",
	"SpeedFactor": 0.9,
	"Route": "Coruscant,Foerost,Kaikielius,Ruan,Jerrilek-Nacon,Empress Teta",
	"Junctions": "Corellian Run,Namadii Corridor,Perlemian Trade Route,Metellos Trade Route,Ag Circuit,Byss Run,Koros-Tython hyperlane",
},
{
	"Name": "Commenor Run",
	"SpeedFactor": 0.9,
	"Route": "Brentaal IV,Tepasi,Korfo II,Caamas,Alderaan,The Graveyard,Tyed Kant,Parkis,Kattada,Commenor",
	"Junctions": "Hydian Way,Perlemian Trade Route,Trellen Trade Route,Quellor Run",
},
{
	"Name": "Vaathkree Trade Corridor",
	"SpeedFactor": 0.9,
	"Route": "Corsin,Comkin V,Telerath,Kroctar,Levian Two,Obroa-skai,Paonid,Gravan Seven,Von-Alai,Contruum,Gizer",
	"Junctions": "Hydian Way,Perlemian Trade Route",
},
{
	"Name": "Randon Run",
	"SpeedFactor": 0.9,
	"Route": "Lantillies,Phaseera,Uyter,Kashyyyk,Rakhuuun,Chamble,Messert,Randon",
	"Junctions": "Perlemian Trade Route,Lesser Lantillian Route,Great Kashyyyk Branch,Durkteel Loop,Nightroad,Pabol Sleheyron,Ootmian Pabol,Trax Tube,Dauntless Run",
},
{
	"Name": "Salin Corridor",
	"SpeedFactor": 0.9,
	"Route": "Salin,Vinsoth,Drackmar,Botajef,Phindar,Bompreil,Gala,Vjun,Lucazec,Columex,Belderone,Trogan,Sy Myrth,Kile II,Komnor,Boonta,Novor 23,Nwarcol Point",
	"Junctions": "Veragi Trade Route,Celanon Spur,Hydian Way,Perlemian Trade Route,Triellus Trade Route,Sisar Run",
},
{
	"Name": "Shaltin Tunnels",
	"SpeedFactor": 0.9,
	"Route": "Ulicia,Atchorb,D'ian,Etti IV,Ession,Kalla VII,Pondut Station,Oslumpex V,Zygerria,Syngia,Lianna",
	"Junctions": "Authority Guardian Corridor,Hydian Way,Trianii Shunt,Etti Route Major,Solenbaran Merchant Route,Lucaya Cross,Tertiary Solenbaran,Authority Arc,Listehol Run,Perlemian Trade Route",
},
{
	"Name": "Tion Trade Route",
	"SpeedFactor": 0.9,
	"Route": "Estaria,Endregaad,Raxus Prime,Tion,Argoon,Rudrig,Clariv,Eredeen,Stalimur,Brigia,Caluula,Dellalt",
	"Junctions": "Perlemian Trade Route,Rudrig-Gbu Way,Pakuuni Drift,Lesser Cronese Arc,Giblim Route",
},
{
	"Name": "Overic Griplink",
	"SpeedFactor": 0.9,
	"Route": "Quermia,Toola,Florn,Ton-Falk Pakuuni,Shaylin 18,Turkana,Munto Codru,Reginard,Ruisto,Karkaris,Mon Cala (Dac)",
	"Junctions": "Perlemian Trade Route,Pakuuni Drift,Minntooine Spur,Tidal Circuit",
},
{
	"Name": "Tingel Route",
	"SpeedFactor": 0.9,
	"Route": "Bonadan,Erysthes,Issagra,Ban-Satir,Gaurick,Joodrudda",
	"Junctions": "Hydian Way,Solenbaran Merchant Route,Tertiary Solenbaran,Tertiary Etti Route",
},
{
	"Name": "Solenbaran Merchant Route",
	"SpeedFactor": 0.9,
	"Route": "Kir,R'alla,Bonadan,Etti IV,Tirsa,Jerrist VI,Saclas",
	"Junctions": "Authority Guardian Corridor,Tingel Route,Shaltin Tunnels,Trianii Shunt,Etti Route Major,Intra-Sector Spur,Tertiary Solenbaran,Rampa Rapids",
},
{
	"Name": "Trianii Shunt",
	"SpeedFactor": 0.9,
	"Route": "Etti IV,Lythos I,Lythos VI-IX,Lythos XIV,Hiit,Fibuli,Brochiib",
	"Junctions": "Etti Route Major,Solenbaran Merchant Route,Shaltin Tunnels,Hydian Way,Authority Guardian Corridor",
},
{
	"Name": "Authority Guardian Corridor",
	"SpeedFactor": 0.9,
	"Route": "Lafra,Dra III,Craci,Drog,Mall'ordian,Ninn,Hiit,Atchorb,Tothis,Kir",
	"Junctions": "Intra-Sector Spur,Etti Route Major,Hydian Way,Lo'Uran-Lythos hyperlane,Trianii Shunt,Shaltin Tunnels,Solenbaran Merchant Route",
},
{
	"Name": "Lo'Uran-Lythos hyperlane",
	"SpeedFactor": 0.9,
	"Route": "Lo'Uran,Ninn,Lythos I,Lythos VI-IX,Lythos XIV",
	"Junctions": "Authority Guardian Corridor,Hydian Way",
},
{
	"Name": "Intra-Sector Spur",
	"SpeedFactor": 0.9,
	"Route": "Reltooine (gas giant),Knolstee,Kail,Craci,Jerrist VI,Biewa",
	"Junctions": "Hydian Way,Authority Guardian Corridor,Solenbaran Merchant Route,Tertiary Solenbaran",
},
{
	"Name": "Listehol Run",
	"SpeedFactor": 0.9,
	"Route": "Listehol,Teagan,Mirial,Sagma system,Sikurd,Gigor,Zygerria",
	"Junctions": "Hydian Way,Shaltin Tunnels",
},
{
	"Name": "Junction-Tierell Loop",
	"SpeedFactor": 0.9,
	"Route": "Feriae Junction,Tertiary Feswe,Selitan,Pinoora,Torque,Jovan III,Vallusk Cluster,Arkuda,Gulvitch,Bronsoon,Povanaria,Durgen's Star,Trinovat,Near Indosa,Presbalin,Tierell",
	"Junctions": "Gordian Reach,Hydian Way,Thesme Trace,Pinooran Spur,Wetyin's Way,Korphir Trace,Bronsoon,Maridun hyperspace route,Hydian Way",
},
{
	"Name": "Thesme Trace",
	"SpeedFactor": 0.9,
	"Route": "Feriae Junction,Thesme",
	"Junctions": "Hydian Way,Junction-Tierell Loop",
},
{
	"Name": "Celanon Spur",
	"SpeedFactor": 0.9,
	"Route": "Dorin,Myomar,Vicondor,Station 88 Spaceport,Vortex,Nentan,T'olan,Dohu VII,Qiilura,Ord Mantell,Dor Nameth,Korvaii,Orocco,Ithor,Noonar,Cademimu V,Paarin Minor,Kebolar,Agamar,Shaum Hii,New Holgha,Vinsoth,Axxila,Ord Cestus,Pedd 4,Celanon",
	"Junctions": "Namadii Corridor,Entralla Route,Braxant Run,Veragi Trade Route,Salin Corridor,Axxila,Tangrene hyperlane,Hydian Way,Burke's Trailing",
},
{
	"Name": "Braxant Run",
	"SpeedFactor": 0.9,
	"Route": "Bandomeer,Selaggis VI,Vahaba asteroid belt,Halmad,Jussafet Four,G'wenee,Storinal,Er'Kit,Borgo Prime,Agamar,Harrod's Planet,Ketaris,Fedje,Vuchelle,Isiring,New Bakstre,Cassander,Garqi,Minashee,Mygeeto,Aris,Ord Trasi,Gwori,Fodro,Kwevron,Venestria,Muunilinst,Jaemus,Bescane,Bastion,Qonto,Xerton Nine",
	"Junctions": "Hydian Way,Celanon Spur,Relgim Run,Entralla Route,Veragi Trade Route,Myto's Arrow",
},
{
	"Name": "Shwuy Exchange",
	"SpeedFactor": 0.9,
	"Route": "Uviuy Exen,Dankayo,Ord Antalaha,Noquivzor,Palanhi,Vakkar",
	"Junctions": "Hydian Way,Namadii Corridor",
},
{
	"Name": "Trellen Trade Route",
	"SpeedFactor": 0.9,
	"Route": "Trellen,Humbarine,Commenor,Rasterous,Zeltros",
	"Junctions": "Hydian Way,Commenor Run,Quellor Run,Lesser Lantillian Route,Great Kashyyyk Branch",
},
{
	"Name": "Quellor Run",
	"SpeedFactor": 0.9,
	"Route": "Commenor,Damoria,Chorax,Vladet,Cato Neimoidia,Hensara III,Talasea,Lankashiir,Quellor",
	"Junctions": "Trellen Trade Route,Commenor Run,Nanth'ri Route",
},
{
	"Name": "Shipwrights' Trace",
	"SpeedFactor": 0.9,
	"Route": "Fondor,Bassadro,Teyr,Foless,Las Lagon,Affa,Atzerri,Chardaan,Tynna,Allanteen VI",
	"Junctions": "Shapani Bypass,Corellian Trade Spine,Hydian Way,Corellian Run",
},
{
	"Name": "Great Gran Run",
	"SpeedFactor": 0.9,
	"Route": "Kinyen,New Balosar,Noe'ha'on,Natalon,Har Binande,Halm,Petabys Station,Tashtor Seneca,Chalcedon,Cerea",
	"Junctions": "Corellian Trade Spine,Cerean Reach,Spar Trade Route",
},
{
	"Name": "D'Aelgoth Trade Route",
	"SpeedFactor": 0.9,
	"Route": "Kassido,Selenius,Ogem,Cyphar,Feenix,Miztoc,Kriselist",
	"Junctions": "Senex-Juvex Loop,Corellian Trade Spine",
},
{
	"Name": "Senex-Juvex Loop",
	"SpeedFactor": 0.9,
	"Route": "Juvex,Kimm Aurek,Kimm Besh,Kimm Cresh,Tinallis,Loovria,Velga Prime,Pieldi,Pirralor,Resti Kel,Malador,Zaria,Anstares,Deminol,Ossiathora,Kassido,Manforgon,Mussubir Three,Cyimarra,Veron,Presteen,Caltinia,Nepoy,Hutlar,Karfeddion,Anturus,Denebia,Kalgo 13",
	"Junctions": "Velga Route,Agarix Trade Route,Kassido Bypass,D'Aelgoth Trade Route,Veron Route,Senex Trace,Anturi Reach",
},
{
	"Name": "Velga Route",
	"SpeedFactor": 0.9,
	"Route": "Velga Prime,Q'mara",
	"Junctions": "Senex-Juvex Loop",
},
{
	"Name": "Agarix Trade Route",
	"SpeedFactor": 0.9,
	"Route": "Pieldi,Dramassia,Umthyg,Dasoor",
	"Junctions": "Senex-Juvex Loop",
},
{
	"Name": "Ison Trade Corridor",
	"SpeedFactor": 0.9,
	"Route": "Indellian,Varonat,Bespin,Anoat,Hoth,Ison,Mataou",
	"Junctions": "Corellian Trade Spine",
},
{
	"Name": "Cerean Reach",
	"SpeedFactor": 0.9,
	"Route": "Cerea,Cheelit,Koba,Riflor,Hirsi,Elbara,Quaensan Prime,Lorta",
	"Junctions": "Spar Trade Route,Great Gran Run,Koda Spur",
},
{
	"Name": "Spar Trade Route",
	"SpeedFactor": 0.9,
	"Route": "Cerea,Abbaji,Annaj,Kuna's Tooth",
	"Junctions": "Annaj-Houche Run,Great Gran Run,Cerean Reach",
},
{
	"Name": "Annaj-Houche Run",
	"SpeedFactor": 0.9,
	"Route": "Annaj,Ovise system,Thonner,Maya Kovel,Vasha,Houche",
	"Junctions": "Spar Trade Route,Ovise Reach",
},
{
	"Name": "Moddell Reach",
	"SpeedFactor": 0.9,
	"Route": "Annaj,Cerea",
	"Junctions": "Annaj-Houche Run,Spar Trade Route,Cerean Reach",
},
{
	"Name": "Ovise Reach",
	"SpeedFactor": 0.9,
	"Route": "Ovise III,Trindello,Zorbia II,Endor (Gas Giant),Endor (Forest Moon)",
	"Junctions": "Annaj-Houche Run,Bakura Trace,Trindello-Endor Route,Shiritoku Way",
},
{
	"Name": "Bakura Trace",
	"SpeedFactor": 0.9,
	"Route": "Endor (Gas Giant),Endor (Forest Moon),Sanyassa IV,Ast Kikorie,Bakura",
	"Junctions": "Ovise Reach,Trindello-Endor Route,Shiritoku Way",
},
{
	"Name": "Shiritoku Way",
	"SpeedFactor": 0.9,
	"Route": "Endor (Gas Giant),Endor (Forest Moon),Timora,Bakura",
	"Junctions": "Ovise Reach,Trindello-Endor Route,Bakura Trace",
},
{
	"Name": "Trindello-Endor Route",
	"SpeedFactor": 0.9,
	"Route": "Endor (Gas Giant),Endor (Forest Moon),Trindello",
	"Junctions": "Ovise Reach,Bakura Trace,Sanctuary Pipeline",
},
{
	"Name": "Sanctuary Pipeline",
	"SpeedFactor": 0.9,
	"Route": "Endor (Gas Giant),Endor (Forest Moon),Murk,Sullust",
	"Junctions": "Bakura Trace,Ovise Reach,Shiritoku Way,Rimma Trade Route,Silvestri Trace,Sanctuary Pipeline",
},
{
	"Name": "Nanth'ri Trade Route",
	"SpeedFactor": 0.9,
	"Route": "Exodeen,Quellor,Antar 4,Gyndine,Fabrin,Mimban,Zaloriis,Attahox,Nanth'ri",
	"Junctions": "Hydian Way,Quellor Run,Ootmian Pabol,Trax Tube",
},
{
	"Name": "Ootmian Pabol",
	"SpeedFactor": 0.9,
	"Route": "Gyndine,Reytha,Chanosant,Trammen,Belasco,Zirulast,New Apsolon,Coachelle Prime,Kyyr system,Ota,Randon,Blimph, Ubrikkia,Kwenn,Keldooine,Nar Bo Sholla,Irith,Du Hutta,Nar Hekka,Nal Hutta",
	"Junctions": "Nanth'ri Route,Nightroad,Terr'skiar Pass,Dauntless Run,Randon Run,Trax Tube,Pabol Sleheyron,Pabol Kreeta,Sheela Run,Oktos Route,Pabol Hutta,Shag Pabol",
},
{
	"Name": "Nightroad",
	"SpeedFactor": 0.9,
	"Route": "Kashyyyk,Tholatin,Mytaranor,Pizilis,Terr'skiar",
	"Junctions": "Randon Run,Great Kashyyyk Branch,Durkteel Loop,Dauntless Run,Ootmian Pabol,Terr'skiar Pass",
},
{
	"Name": "Great Kashyyyk Branch",
	"SpeedFactor": 0.9,
	"Route": "Zeltros,Umbara,Zavian Abyss,Couronne system,Kashyyyk,Balamak,Charros IV",
	"Junctions": "Trellen Trade Route,Durkteel Loop,Nightroad,Randon Run",
},
{
	"Name": "Durkteel Loop",
	"SpeedFactor": 0.9,
	"Route": "Kashyyyk,Kwookrrr,Sneeve,Durkteel,Yitabo",
	"Junctions": "Great Kashyyyk Branch,Nightroad,Randon Run",
},
{
	"Name": "Dauntless Run",
	"SpeedFactor": 0.9,
	"Route": "Ota,Rorgam,Pizilis",
	"Junctions": "Ootmian Pabol,Nightroad",
},
{
	"Name": "Terr'skiar Pass",
	"SpeedFactor": 0.9,
	"Route": "Terr'skiar,Bissillirus,Deysum",
	"Junctions": "Ootmian Pabol,Trax Tube",
},
{
	"Name": "Trax Tube",
	"SpeedFactor": 0.9,
	"Route": "Randon,Deysum III,Lexrul,Uogo'cor,Nanth'ri,Nixor,Daalang",
	"Junctions": "Randon Run,Pabol Sleheyron,Ootmian Pabol,Dauntless Run,Terr'skiar Pass,Oktos Route,Nanth'ri Route,Gamor Run,Bothan Run",
},
{
	"Name": "Pabol Sleheyron",
	"SpeedFactor": 0.9,
	"Route": "Formos,Prishella system,Little Kessel,Aeneid system,Zerm,Randa,Ulmatra,Sleheyron,Nimban,Nar Kreeta,Ilos Minor,Ilos,Chalacta,Yitabo,Randon",
	"Junctions": "Triellus Trade Route,Kessel Run,Kessel Trade Corridor,The Dead Road,Pabol Hutta,Sisar Run,Pabol Kreeta,Ilosian Spur,Durkteel Loop,Ootmian Pabol,Randon Run,Trax Tube",
},
{
	"Name": "The Dead Road",
	"SpeedFactor": 0.9,
	"Route": "Nimia,Kafane,Ulmatra,Zisia,Elgit,Usk,Saqqar,Tisht,M'Hanna,Varl",
	"Junctions": "Pabol Sleheyron,Pabol Hutta",
},
{
	"Name": "Pabol Hutta",
	"SpeedFactor": 0.9,
	"Route": "Nal Hutta,Hosko,Varl,Gos Hutta,Mulatan,Sleheyron,Topa",
	"Junctions": "Oktos Route,Ootmian Pabol,Shag Pabol,The Dead Road,Pabol Sleheyron,Sisar Run",
},
{
	"Name": "Oktos Route",
	"SpeedFactor": 0.9,
	"Route": "Nal Hutta,Kleeva,Toydaria,Tol Amn",
	"Junctions": "Ootmian Pabol,Pabol Hutta,Shag Pabol,Trax Tube",
},
{
	"Name": "Shag Pabol",
	"SpeedFactor": 0.9,
	"Route": "Nal Hutta,Rorak 4,Rorak 5,Diyu,Ylesia,Ziugen,Outland Transit,Lirra,Teth",
	"Junctions": "Oktos Route,Ootmian Pabol,Pabol Hutta,Gamor Run,The Sy-Y,Triellus Trade Route",
},
{
	"Name": "The Sy-Y",
	"SpeedFactor": 0.9,
	"Route": "Ylesia,Syvris",
	"Junctions": "Shag Pabol,Hollastin Run,Triellus Trade Route",
},
{
	"Name": "Hollastin Run",
	"SpeedFactor": 0.9,
	"Route": "Circumtore,Affavan,Hollastin,Aylayl,Tsyk,Unagin,Syvris",
	"Junctions": "Gamor Run,Kaaga Run,Pando Spur,The Sy-Y,Triellus Trade Route",
},
{
	"Name": "Kaaga Run",
	"SpeedFactor": 0.9,
	"Route": "Circumtore,Carnovia,Nar Kaaga,Dohlban,Void Station,Bothawui",
	"Junctions": "Gamor Run,Hollastin Run,Tatooine Dash,Bothan Run,Manda Merchant Route,Reena Trade Route",
},
{
	"Name": "Tatooine Dash",
	"SpeedFactor": 0.9,
	"Route": "Nar Kaaga,Manda,Tatooine",
	"Junctions": "Kaaga Run,Manda Merchant Route,Manda-Roon Merchant Route,Corellian Skip Run,The Crystal Passage,Old Corellian Run,Triellus Trade Route",
},
{
	"Name": "Manda Merchant Route",
	"SpeedFactor": 0.9,
	"Route": "Bothawui,Kothlis,Thoran,Zygia,Holess,Boranda,Manda,Dennaskar,Pastil,Hishyim,Rishi,Ukio,Molavar",
	"Junctions": "Bothan Run,Kaaga Run,Reena Trade Route,Manda-Roon Merchant Route,Tatooine Dash,Triellus Trade Route",
},
{
	"Name": "Bothan Run",
	"SpeedFactor": 0.9,
	"Route": "Bothawui,Moonus Mandel,Lannik,Daalang",
	"Junctions": "Manda Merchant Route,Reena Trade Route,Kaaga Run,Gamor Run,Trax Tube",
},
{
	"Name": "Manda-Roon Merchant Route",
	"SpeedFactor": 0.9,
	"Route": "Manda,Roon",
	"Junctions": "Manda Merchant Route,Tatooine Dash,Death Wind Corridor",
},
{
	"Name": "Lesser Lantillian Route",
	"SpeedFactor": 0.9,
	"Route": "Zeltros,Merson,Taboon,Ambria,Onderon,Porus Vida,Vena,Nazzri,Avenelle,Uyter,Togoria,Charros IV,Bimmisaari,Peg Shar I,Pusat Station,Boonta,Junkfort system",
	"Junctions": "Trellen Trade Route,Great Kashyyyk Branch,Randon Run,Great Kashyyyk Branch,Ilosian Spur,Triellus Trade Route,Cadma Conduit",
},
{
	"Name": "Ilosian Spur",
	"SpeedFactor": 0.9,
	"Route": "Bimmisaari,Xoman III,Boz Pity,Alee,Tal Nami,Ilos Minor",
	"Junctions": "Lesser Lantillian Route,Pabol Sleheyron",
},
{
	"Name": "Cadma Conduit",
	"SpeedFactor": 0.9,
	"Route": "Junkfort system,Dagelin Minor,Oseon VII,Scillal,Lekua V,Cadma,Zebitrope IV",
	"Junctions": "Lesser Lantillian Route,Triellus Trade Route,Falko Run,Arleen Loop",
},
{
	"Name": "Falko Run",
	"SpeedFactor": 0.9,
	"Route": "Oseon VII,Arleen,Ringneldia II,Dilonexa XXIII,Uaua,Falko,Antipose,Paulking XIV,Douglas III",
	"Junctions": "Cadma Conduit,Arleen Loop",
},
{
	"Name": "Arleen Loop",
	"SpeedFactor": 0.9,
	"Route": "Arleen,Rafa IV,Dela III,Lekua V",
	"Junctions": "Cadma Conduit,Falko Run",
},
{
	"Name": "Sheela Run",
	"SpeedFactor": 0.9,
	"Route": "Nar Hekka,Sheela",
	"Junctions": "Ootmian Pabol",
},
{
	"Name": "Sisar Run",
	"SpeedFactor": 0.9,
	"Route": "Nwarcol Point,Sriluur,Station 3,Terman Station,Sespe,Dirha,Cyborrea,Sionia,Nimban",
	"Junctions": "Salin Corridor,Pabol Hutta,Pabol Sleheyron,Ac'fren Spur",
},
{
	"Name": "Ac'fren Spur",
	"SpeedFactor": 0.9,
	"Route": "Sriluur,Ques,Tas-La",
	"Junctions": "Sisar Run",
},
{
	"Name": "Pando Spur",
	"SpeedFactor": 0.9,
	"Route": "Hollastin,Xolu,Far Pando,Near Pando",
	"Junctions": "Hollastin Run",
},
{
	"Name": "The Crystal Passage",
	"SpeedFactor": 0.9,
	"Route": "Tatooine,Geonosis,Cranan 12,Vactooine,Tarnoonga,Cirus II",
	"Junctions": "5709-DC Shipping Lane,Corellian Skip Run,Old Corellian Run,Rycar's Run,Tatooine Dash,    Triellus Trade Route",
},
{
	"Name": "5709-DC Shipping Lane",
	"SpeedFactor": 0.9,
	"Route": "Enarc,Tattoine,",
	"Junctions": "Triellus Trade Route",
},
{
	"Name": "Rycar's Run",
	"SpeedFactor": 0.9,
	"Route": "Roche asteroid field,Tatooine,Kessel,Kiffex,Nar Shaddaa",
	"Junctions": "Perlemian Trade Route,5709-DC Shipping Lane,Corellian Skip Run,The Crystal Passage,Old Corellian Run,Tatooine Dash,Triellus Trade Route,Kessel Run,Kessel Trade Corridor,Oktos Route,Ootmian Pabol,Pabol Hutta,Shag Pabol",
},
{
	"Name": "Relgim Run",
	"SpeedFactor": 0.9,
	"Route": "Fedje,Fest,Devon Four,Generis,Markbee's Star,Nam'ta,Horuz,Mantooine,Vykos,Aris,Marmoth,Cezith,Endoraan,Gelda,Delephr,Ord Thoden",
	"Junctions": "Braxant Run,Entralla Route",
},
{
	"Name": "Entralla Route",
	"SpeedFactor": 0.9,
	"Route": "Ord Mantell,Qiilura,Yout,Tyan,Ord Tessebok,Gonmore,Obredaan,Lonnaw,Orinda,Wistril,JanFathal,Domgrin,Ywllandr,Borosk,Prefsbelt IV,Ompersan,Yaga Minor,Capza,Entralla,Endoraan,Bisellia,Muunilinst",
	"Junctions": "Celanon Spur,Relgim Run,Braxant Run",
},
{
	"Name": "Veragi Trade Route",
	"SpeedFactor": 0.9,
	"Route": "Salin,Ciutric IV,Corvis Minor,Argazda,Bimmiel,Birgis,Seline,Sernpidal,Veragi,Trassitan,Dubrillion,Ahakista,Dantooine,Sinsang,Anx Minor,Ord Trasi",
	"Junctions": "Salin Corridor,Myto's Arrow,Braxant Run",
},
{
	"Name": "Myto's Arrow",
	"SpeedFactor": 0.9,
	"Route": "Dantooine,Angor,Gabredor III,Jaemus",
	"Junctions": "Veragi Trade Route,Braxant Run",
},
{
	"Name": "Axxila–Tangrene hyperlane",
	"SpeedFactor": 0.9,
	"Route": "Axxila,Vandyne,Camden,Edusa,Tangrene",
	"Junctions": "Celanon Spur",
},
{
	"Name": "Gordian Reach",
	"SpeedFactor": 0.9,
	"Route": "Feriae system,Belderone system",
	"Junctions": "Hydian Way,Perlemian Trade Route",
},
{
	"Name": "Pinooran Spur",
	"SpeedFactor": 0.9,
	"Route": "Kushibah,Mogoshyn,Betshish,Kli'aar,Marrovia,Ladarra,Krylon,Pinoora",
	"Junctions": "Junction-Tierell Loop,Yavin Bypass",
},
{
	"Name": "Junction-Tierell Loop",
	"SpeedFactor": 0.9,
	"Route": "Feriae Junction,Tertiary Feswe,Selitan,Pinoora,Torque,Jovan III,Vallusk Cluster,Arkuda,Gulvitch,Bronsoon,Povanaria,Durgen's Star,Trinovat,Near Indosa,Presbalin,Tierell",
	"Junctions": "Gordian Reach,Hydian Way,Thesme Trace,Pinooran Spur,Wetyin's Way,Korphir Trace,Bronsoon–Maridun hyperspace route,Hydian Way",
},
{
	"Name": "Wetyin's Way",
	"SpeedFactor": 0.9,
	"Route": "Jovan III,Vaal,Glade,Wetyin's Colony",
	"Junctions": "Junction-Tierell Loop,Yavin Bypass",
},
{
	"Name": "Korphir Trace",
	"SpeedFactor": 0.9,
	"Route": "Korphir,The Roil,Arkuda",
	"Junctions": "Junction-Tierell Loop",
},
{
	"Name": "Bronsoon–Maridun hyperspace route",
	"SpeedFactor": 0.9,
	"Route": "Junction-Tierell Loop",
	"Junctions": "Gordian Reach,Junction-Tierell Loop",
},
{
	"Name": "Yavin Bypass",
	"SpeedFactor": 0.9,
	"Route": "Krylon,Yavin 4,Vaal",
	"Junctions": "Pinooran Spur,Gordian Reach,Wetyin's Way",
},
{
	"Name": "Tertiary Solenbaran",
	"SpeedFactor": 0.9,
	"Route": "Saclas,Duroon,Biewa,Kalla VII,Issagra,Deltooine",
	"Junctions": "Solenbaran Merchant Route,Intra-Sector Spur,Shaltin Tunnels,Tingel Route,Authority Guardian Corridor",
},
{
	"Name": "Etti Route Major",
	"SpeedFactor": 0.9,
	"Route": "Kail,Davirien,Drog,Etti IV",
	"Junctions": "Intra-Sector Spur,Authority Guardian Corridor,Trianii Shunt,Solenbaran Merchant Route,Shaltin Tunnels",
},
{
	"Name": "Rampa Rapids",
	"SpeedFactor": 0.9,
	"Route": "R'alla,Rampa III",
	"Junctions": "Solenbaran Merchant Route",
},
{
	"Name": "Tertiary Etti Route",
	"SpeedFactor": 0.9,
	"Route": "Gaurick,Ocsin,Farana,Hull's Star,Mytus VII",
	"Junctions": "Authority Guardian Corridor,Tingel Route",
},
{
	"Name": "Pakuuni Drift",
	"SpeedFactor": 0.9,
	"Route": "Pakuuni,Gbu,Mullan,Brigia",
	"Junctions": "Overic Griplink,Rudrig-Gbu Way,Tion Trade Route",
},
{
	"Name": "Rudrig-Gbu Way",
	"SpeedFactor": 0.9,
	"Route": "Gbu,Rudrig",
	"Junctions": "Tion Trade Route,Pakuuni Drift",
},
{
	"Name": "Minntooine Spur",
	"SpeedFactor": 0.9,
	"Route": "Mon Cala (Dac),Minntooine",
	"Junctions": "Giblim Route,Prously's Rim Run,Overic Griplink",
},
{
	"Name": "Giblim Route",
	"SpeedFactor": 0.9,
	"Route": "Caluula,Dellalt,Minntooine",
	"Junctions": "Lesser Cronese Arc,Tion Trade Route,Minntooine",
},
{
	"Name": "Prously's Rim Run",
	"SpeedFactor": 0.9,
	"Route": "Mon Cala (Dac),Pammant,Mantan,New Heurkea,Sanctuary,Kamdon,Dornea,Baros",
	"Junctions": "Overic Griplink,Minntooine Spur,Tidal Circuit",
},
{
	"Name": "Greater Cronese Arc",
	"SpeedFactor": 0.9,
	"Route": "Arcan IV,Janilis VII,Chandaar,Oor VII,Barancar,Soruus,Pasmin,Arramanx,Duinarbulon,Derellium",
	"Junctions": "Perlemian Trade Route,Kismaano Bypass,Indrexu Route,Lesser Cronese Arc",
},
{
	"Name": "Lesser Cronese Arc",
	"SpeedFactor": 0.9,
	"Route": "Derellium,Eibon,Algor,Saheelindeel,Caluula",
	"Junctions": "Greater Cronese Arc,Indrexu Route,Tion Trade Route",
},
{
	"Name": "Indrexu Route",
	"SpeedFactor": 0.9,
	"Route": "Dravione,Argai,Corlass,Panna,Derellium",
	"Junctions": "Cadinth Run,Desevran Trace,Greater Cronese Arc,Lesser Cronese Arc",
},
{
	"Name": "Kismaano Bypass",
	"SpeedFactor": 0.9,
	"Route": "Cadinth,Kismaano,Gadon 3,Arramanx",
	"Junctions": "Cadinth Run,Greater Cronese Arc",
},
{
	"Name": "Cadinth Run",
	"SpeedFactor": 0.9,
	"Route": "Lianna,Spinax III,Cadinth,Embaril,Voss,Jaminere,Dravione",
	"Junctions": "Perlemian Trade Route,Kismaano Bypass,Indrexu Route,Desevran Trace",
},
{
	"Name": "Desevran Trace",
	"SpeedFactor": 0.9,
	"Route": "Desevro,Folende,Omman,Amarin,Corlax 4,Dravione",
	"Junctions": "Perlemian Trade Route,Cadinth Run,Indrexu Route",
},
{
	"Name": "Tidal Circuit",
	"SpeedFactor": 0.9,
	"Route": "Mon Cala (Dac),Pinperu,Damendine,Krinemonen,Hinakuu,Sanctuary",
	"Junctions": "Prously's Rim Run",
},
{
	"Name": "Lucaya Cross",
	"SpeedFactor": 0.9,
	"Route": "Media,Ession,Saffalore",
	"Junctions": "Shaltin Tunnels",
},
{
	"Name": "Agricultural Circuit",
	"SpeedFactor": 0.9,
	"Route": "Cal-Seti,Fresia,Galand,Worru'du,Salliche,Stassia,Ruan,Yulant,Aargau,Broest,Xorth",
	"Junctions": "Metellos Trade Route,Koros Trunk Line,Corellian Run",
},
{
	"Name": "Byss Run",
	"SpeedFactor": 0.9,
	"Route": "Empress Teta,Keeara Major,Prakith,Byss",
	"Junctions": "Koros Trunk Line",
},
{
	"Name": "Koros-Tython hyperlane",
	"SpeedFactor": 0.9,
	"Route": "Koros Major,Tython",
	"Junctions": "Koros Trunk Line",
},
{
	"Name": "Elrood-Derilyn Trade Route",
	"SpeedFactor": 0.9,
	"Route": "Elrood,Kidron,Bodrin,Coyn,Korad,Merisee,Torina,Derilyn",
	"Junctions": "Coyn Route,The Extreme",
},
{
	"Name": "The Extreme",
	"SpeedFactor": 0.9,
	"Route": "Torina,Derilyn",
	"Junctions": "Elrood-Derilyn Trade Route",
},
{
	"Name": "Sanrafsix Corridor",
	"SpeedFactor": 0.9,
	"Route": "Sanrafsix,Fostin Nine,Syned,Omwat,Kabal,Dravian Station,Sevarcos II,Kirdo III,Ma'ar Shaddam,Cotellier",
	"Junctions": "Duros Space Run,Sharlissian Trade Corridor",
},
{
	"Name": "Yankirk Route",
	"SpeedFactor": 0.9,
	"Route": "Eriadu",
	"Junctions": "Rimma Trade Route,Hydian Way,Nothoiin Corridor,Lipsec Run",
},
{
	"Name": "Lutrillian Cross",
	"SpeedFactor": 0.9,
	"Route": "Mijos,Lutrillia",
	"Junctions": "Nothoiin Corridor",
},
{
	"Name": "Procopian Shipping Lane",
	"SpeedFactor": 0.9,
	"Route": "Tallaan,Neona,Reyna,Procopia,Obulette,Tumus,Bianas,Reena",
	"Junctions": "Giju Run,Shapani Bypass,Three Ellas Run,Calipsa Run,Leozi Route,Caloria Run",
},
{
	"Name": "Giju Run",
	"SpeedFactor": 0.9,
	"Route": "Tallaan,Giju,Omar,Illodia,Dahrtag,Hjaff,Atrisia",
	"Junctions": "Shapani Bypass,Procopian Shipping Lane,Rimma Trade Route",
},
{
	"Name": "Three Ellas Run",
	"SpeedFactor": 0.9,
	"Route": "Sorella,Dorella,Pernella",
	"Junctions": "Dorella-Doris hyperlane,Sorella-Tanya hyperlane",
},
{
	"Name": "Dorella-Doris hyperlane",
	"SpeedFactor": 0.9,
	"Route": "Dorella,Doris",
	"Junctions": "Three Ellas Run",
},
{
	"Name": "Sorella-Tanya hyperlane",
	"SpeedFactor": 0.9,
	"Route": "Sorella,Tanya",
	"Junctions": "Three Ellas Run",
},
{
	"Name": "Calipsa Run",
	"SpeedFactor": 0.9,
	"Route": "Calipsa,New Javis,Lorenz,Nella,Estaph,Grella",
	"Junctions": "Calipsa Province,Mecetti Province,Procopian Shipping Lane",
},
{
	"Name": "Calipsa Province",
	"SpeedFactor": 0.9,
	"Route": "Betolio,Calipsa,Coorimbus,Dampher,Grella,Jinda,Kamper,Lorenz,Netolio,New Javis,Riesa,Setolio,Shifa",
	"Junctions": "Calipsa Run",
},
{
	"Name": "Mecetti Province",
	"SpeedFactor": 0.9,
	"Route": "Bianas,Blyte,Dorellia,Estaph,Javis,Lastelle,Nella,Nyssa,Obulette,Pella,Pozzi,Tanda,Tanya,Tanzis,Tumus",
	"Junctions": "Leozi Route,Procopian Shipping Lane,Calipsa Run",
},
{
	"Name": "Trans Gulf Route",
	"SpeedFactor": 0.9,
	"Route": "Pii,Vuzsa,Piroket",
	"Junctions": "Old Corellian Run,Triellus Trade Route",
},
{
	"Name": "Leozi Route",
	"SpeedFactor": 0.9,
	"Route": "Javis,Tanda,Pozzi,Tanya,Tanzis",
	"Junctions": "Procopian Shipping Lane,Calipsa Run",
},
{
	"Name": "Najiba Loop",
	"SpeedFactor": 0.9,
	"Route": "Issor,Najiba,Vasch",
	"Junctions": "Triellus Trade Route,Vaschean Way",
},
{
	"Name": "Vaschean Way",
	"SpeedFactor": 0.9,
	"Route": "Arkanis,Huldamun,Vasch,Mika system,Heffrin,Khubeaie",
	"Junctions": "Corellian Run,Old Correllian Run",
},
{
	"Name": "Five Veils Route",
	"SpeedFactor": 0.9,
	"Route": "Farstine,Ninzam VI,Trigalis,Stend,Vergesso Asteroids,Bajic,Vohai,Elshandruu Pica,Suarbi 7,Svivren,Skynara",
	"Junctions": "Triellus Trade Route,Llanic Spice Run",
},
{
	"Name": "Kira Run",
	"SpeedFactor": 0.9,
	"Route": "Lazerian IV,Kira IV,Ropagi II",
	"Junctions": "Harrin Trade Corridor,Enarc Run",
},
{
	"Name": "Metellos–Ilum hyperlane",
	"SpeedFactor": 0.9,
	"Route": "Metellos–Ilum",
	"Junctions": "Metellos Trade Route",
},
{
	"Name": "Hyabb-Twith Corridor",
	"SpeedFactor": 0.9,
	"Route": "Hyabb,Voon,Twith",
	"Junctions": "Namadii Corridor",
},
{
	"Name": "Rago Run",
	"SpeedFactor": 0.9,
	"Route": "Rago,Sinton,Gilatter VIII,Ansion,Keitum",
	"Junctions": "Namadii Corridor,Murgo Choke",
},
{
	"Name": "Murgo Choke",
	"SpeedFactor": 0.9,
	"Route": "Rago,Murgo,Utegetu Nebula",
	"Junctions": "Rago Run",
},
{
	"Name": "Cranan-Excarga Route",
	"SpeedFactor": 0.9,
	"Route": "Vor Deo,Gedi 4,Cranan 12,Melnea's World,Excarga",
	"Junctions": "Corellian Run,Old Corellian Run,The Crystal Passage",
},
{
	"Name": "Caloria Run",
	"SpeedFactor": 0.9,
	"Route": "Caloria,Tanger,Reena,Tillo system",
	"Junctions": "Procopian Shipping Lane",
},
{
	"Name": "Burke's Trailing",
	"SpeedFactor": 0.9,
	"Route": "Ponemah Terminal,Jakku,Adrathorpe,Jedha,Ord Mantell",
	"Junctions": "Celanon Spur,Entralla Route",
},
{
	"Name": "Hidakai Pool",
	"SpeedFactor": 0.9,
	"Route": "Daupherm,Botor system,Abregado-rae,Giju,Yag'Dhul",
	"Junctions": "Giju Run,Corellian Trade Spine",
},
{
	"Name": "Biox Detour",
	"SpeedFactor": 0.9,
	"Route": "Takodana,Ring of Kafrene,Malastare",
	"Junctions": "Rimma Trade Route,Hydian Way",
},
{
	"Name": "The Loop",
	"SpeedFactor": 0.9,
	"Route": "Mijos,Shuldene,Lutrillia",
	"Junctions": "Lutrillian Cross,Cerean Reach,Koda Spur,Lutrillia,Darlyn Boda",
},
{
	"Name": "Koda Spur",
	"SpeedFactor": 0.9,
	"Route": "Lutrillia,Ryoone,Urn-Aram,Koda Space Station",
	"Junctions": "Lutrillian Cross,Cerean Reach",
},
{
	"Name": "Lutrillia–Darlyn Boda Trade Route",
	"SpeedFactor": 0.9,
	"Route": "Lutrillia,Darlyn Boda",
	"Junctions": "Corellian Trade Spine,Lutrillian Cross",
},
];
