// JSON list of locations
const locations = [
{
	"Name": "Alderaan",
	"Region": "Core Worlds",
	"Sector": "Alderaan",
	"System": "Alderaan",
	"Inhabitants": "Humans (Alderaanian)",
	"Starport": 0,
	"Capital City": "Aldera",
	"Map": "M-10",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "forest,mountain,plains",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Alderaan",
	"ImperialPresence": 4,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Aleen (surface)",
	"Region": "Mid Rim",
	"Sector": "Bright Jewel",
	"System": "Aleen",
	"Inhabitants": "Aleena, Kindalo",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "L-7",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": -4,
	"Terrain": "rocky mesa,desert plains,isolated forest",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Aleen/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Aleen (underground)",
	"Region": "Mid Rim",
	"Sector": "Bright Jewel",
	"System": "Aleen",
	"Inhabitants": "Aleena, Kindalo",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "L-7",
	"Climate": "temperate",
	"Atmosphere": "Type II",
	"Precipitation": -5,
	"Terrain": "cavern,luminescent vegetation grove",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Aleen/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Aloxl",
	"Region": "Deep Core",
	"Sector": "Deep Core",
	"System": "Aloxl",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "L-10",
	"Climate": "hot",
	"Atmosphere": "Type IV",
	"Precipitation": -3,
	"Terrain": "arid plains,extreme heat during hot cycle",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Aloxl/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Ando",
	"Region": "Mid Rim",
	"Sector": "Lambda",
	"System": "Ando",
	"Inhabitants": "Aqualish",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Q-15",
	"Climate": "temperate,humid",
	"Atmosphere": "Type I",
	"Precipitation": 4,
	"Terrain": "cave,rainforest,saltwater ocean,swamp,small rocky island",
	"Gravity": 1.22,
	"URL": "https://starwars.fandom.com/wiki/Ando/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Anoat",
	"Region": "Outer Rim",
	"Sector": "Anoat",
	"System": "Anoat",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "K-18",
	"Climate": "hot",
	"Atmosphere": "Type II",
	"Precipitation": 0,
	"Terrain": "polluted sludge",
	"Gravity": 0.85,
	"URL": "https://starwars.fandom.com/wiki/Anoat/Legends",
	"ImperialPresence": 1,
	"OldWestiness": -1,
	"Megafauna": -1,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Ansion",
	"Region": "Mid Rim",
	"Sector": "Churnis",
	"System": "Ansion",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "I-6",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "grassland,hill,plateau",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Ansion/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Arbra",
	"Region": "Outer Rim",
	"Sector": "Bon'nyuw-Luq",
	"System": "Arbra",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "N-17",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "rainforest,jungle,mountain,cave,ice cap,small sea,volcanic",
	"Gravity": 0.97,
	"URL": "https://starwars.fandom.com/wiki/Arbra/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Atraken",
	"Region": "Outer Rim",
	"Sector": "Rolion",
	"System": "Atraken",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Q-7",
	"Climate": "cool",
	"Atmosphere": "Type III",
	"Precipitation": 1,
	"Terrain": "cave,crater,mountain,ocean,poisonous water",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Atraken/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Auratera",
	"Region": "Outer Rim",
	"Sector": "Vorzyd",
	"System": "Auratera",
	"Inhabitants": "Various",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "R-6",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "mountain,forest,plains",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Auratera/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Bakura",
	"Region": "Wild Space",
	"Sector": "Bakura",
	"System": "Bakura",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Salis D'aar",
	"Map": "G-16",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "forest,plains,mountain,small sea,river,valley",
	"Gravity": 1.05,
	"URL": "https://starwars.fandom.com/wiki/Bakura/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Bardotta",
	"Region": "Colonies",
	"Sector": "Shasos",
	"System": "Bardotta",
	"Inhabitants": "Bardottans",
	"Starport": 0,
	"Capital City": "Bardotta Capital City",
	"Map": "K-13",
	"Climate": "cold",
	"Atmosphere": "Type I",
	"Precipitation": 1,
	"Terrain": "mountain,highland,plains,ice cap",
	"Gravity": 0.95,
	"URL": "https://starwars.fandom.com/wiki/Bardotta",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Bespin",
	"Region": "Outer Rim",
	"Sector": "Anoat",
	"System": "Bespin",
	"Inhabitants": "Humans, Ugnaughts",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "K-18",
	"Climate": "temperate and normal gravity in the Life Zone",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "gas giant,cloudscape",
	"Gravity": 1.5,
	"URL": "https://starwars.fandom.com/wiki/Bespin/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Bothawui",
	"Region": "Mid Rim",
	"Sector": "Bothan Space",
	"System": "Both",
	"Inhabitants": "Bothans",
	"Starport": 0,
	"Capital City": "Drev'starn",
	"Map": "R-14",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "plains,mountain,forest,urban",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Bothawui/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Byss",
	"Region": "Deep Core",
	"Sector": "Unknown",
	"System": "Beshqek",
	"Inhabitants": "Unknown",
	"Starport": "2",
	"Capital City": "Unknown",
	"Map": "K-11",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "urban sprawl,plateau,canyon,lake",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Byss/Legends",
	"ImperialPresence": 5,
	"OldWestiness": 0,
	"Megafauna": "-5",
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 3,
	"WeaponRifle": 2,
	"WeaponHeavy": 1,
	"ArmorLight": 2,
	"ArmorPower": 1,
	"Slavery": 5,
	"DroidsRestricted": 2,
	"DroidsFree": 1,
	"Cybernetics": 1,
	"Spice": -1,
	"Drugs": -1,
	"Ores": -1,
	"Trespassing": -2,
	"Poison": 0,
	"Military": 3,
	"Slicing": -3,
	"Theft": -3,
	"Bribery": 0,
	"Livestock": -1,
	"Vehicles": 1,
	"RidingBeasts": -2
},
{
	"Name": "Carida",
	"Region": "Colonies",
	"Sector": "Carida",
	"System": "Carida",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "M-9",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 1,
	"Terrain": "forest,desert,glacier,jungle,arctic tundra",
	"Gravity": 1.98,
	"URL": "https://starwars.fandom.com/wiki/Carida/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Corellia",
	"Region": "Core Worlds",
	"Sector": "Corellian",
	"System": "Corellia",
	"Inhabitants": "Humans (Corellian), Various",
	"Starport": 0,
	"Capital City": "Coronet City",
	"Map": "M-11",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "plains,urban,hill,forest,mesa,mountain,island,jungle",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Corellia/Legends",
	"ImperialPresence": 5,
	"OldWestiness": -5,
	"Megafauna": -5,
	"Rarity": 0,
	"Criticism": 4,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Coruscant",
	"Region": "Core Worlds",
	"Sector": "Corusca",
	"System": "Coruscant",
	"Inhabitants": "Various",
	"Starport": "5",
	"Capital City": "Galactic City",
	"Map": "L-9",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "ecumenopolis",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Coruscant",
	"ImperialPresence": 5,
	"OldWestiness": -5,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": -3,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Dathomir",
	"Region": "Outer Rim",
	"Sector": "Quelli",
	"System": "Dathomir",
	"Inhabitants": "Fromprath (later exiled), Zabraks (Dathomirian)",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "O-6",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "desert,forest,jungle,mountain",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Dathomir/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Dorin",
	"Region": "Expansion Region",
	"Sector": "Deadalis",
	"System": "Dorin",
	"Inhabitants": "Kel Dor",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "J-8",
	"Climate": "temperate,stormy",
	"Atmosphere": "Type III",
	"Precipitation": 2,
	"Terrain": "mountain,valley,plateau",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Dorin/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 1,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Endor",
	"Region": "Outer Rim",
	"Sector": "Moddell",
	"System": "Endor",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "H-16",
	"Climate": "chemical and magnetic storms",
	"Atmosphere": "Type IV",
	"Precipitation": 5,
	"Terrain": "gas giant",
	"Gravity": 2.5,
	"URL": "https://starwars.fandom.com/wiki/Endor_(location)/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 4,
	"Criticism": -4,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Falleen",
	"Region": "Mid Rim",
	"Sector": "Doldur",
	"System": "Falleen",
	"Inhabitants": "Falleen",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "P-15",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "jungle,mountain,plains,industrial",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Falleen_(location)/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Felucia",
	"Region": "Outer Rim",
	"Sector": "Thanium",
	"System": "Felucia",
	"Inhabitants": "Felucians, Jungle Felucians",
	"Starport": 0,
	"Capital City": "Kway Teow",
	"Map": "R-6",
	"Climate": "hot,humid",
	"Atmosphere": "Type I",
	"Precipitation": 4,
	"Terrain": "jungle,swamp",
	"Gravity": 0.75,
	"URL": "https://starwars.fandom.com/wiki/Felucia",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Gabredor III",
	"Region": "Outer Rim",
	"Sector": "Myto",
	"System": "Gabredor",
	"Inhabitants": "Defel,Human",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Unknown",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 4,
	"Terrain": "jungle",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Gabredor_III/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 5,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Galaan",
	"Region": "Outer Rim",
	"Sector": "Corva",
	"System": "Galaan",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "P-4",
	"Climate": "frigid",
	"Atmosphere": "Type IV",
	"Precipitation": 5,
	"Terrain": "gas giant",
	"Gravity": 2,
	"URL": "https://starwars.fandom.com/wiki/Galaan/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -99,
	"Criticism": -5,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Galzez",
	"Region": "Mid Rim",
	"Sector": "Dustig",
	"System": "Galzez",
	"Inhabitants": "Dugs",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "M-17",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "mountain,orange crystal",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Galzez",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Gand",
	"Region": "Outer Rim",
	"Sector": "Shadola",
	"System": "Gand",
	"Inhabitants": "Gand",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "T-8",
	"Climate": "(unknown)",
	"Atmosphere": "Type IV",
	"Precipitation": 1,
	"Terrain": "ammonia mist,rocky hill",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Gand_(location)/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -4,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Gentes",
	"Region": "Outer Rim",
	"Sector": "Anoat",
	"System": "Anoat",
	"Inhabitants": "Ugnaughts",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Unknown",
	"Climate": "cool",
	"Atmosphere": "Type II",
	"Precipitation": -1,
	"Terrain": "wasteland",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Gentes/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 5,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Geonosis",
	"Region": "Outer Rim",
	"Sector": "Arkanis",
	"System": "Geonosis",
	"Inhabitants": "Geonosians",
	"Starport": 0,
	"Capital City": "Stalgasin hive",
	"Map": "R-16",
	"Climate": "hot,arid",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "desert,mesa,mountain",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Geonosis",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Gravlex Med",
	"Region": "Outer Rim",
	"Sector": "Raioballo",
	"System": "Gravlex Med",
	"Inhabitants": "Anx",
	"Starport": 0,
	"Capital City": "Ozlyn Gox",
	"Map": "L-4",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": -1,
	"Terrain": "polluted wasteland,mountain,cave",
	"Gravity": 1.5,
	"URL": "https://starwars.fandom.com/wiki/Gravlex_Med/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Haruun Kal",
	"Region": "Mid Rim",
	"Sector": "Dustig",
	"System": "Al'Har",
	"Inhabitants": "Humans, Korun",
	"Starport": 0,
	"Capital City": "Pelek Baw",
	"Map": "M-17",
	"Climate": "temperate",
	"Atmosphere": "Type II",
	"Precipitation": 2,
	"Terrain": "toxic cloudsea,plateau,volcanic,jungle",
	"Gravity": 0.98,
	"URL": "https://starwars.fandom.com/wiki/Haruun_Kal/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Hoth",
	"Region": "Outer Rim",
	"Sector": "Anoat",
	"System": "Hoth",
	"Inhabitants": "Various",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "K-18",
	"Climate": "frigid",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "canyon,frozen plains,ice cave,mountain range,tundra",
	"Gravity": 1.1,
	"URL": "https://starwars.fandom.com/wiki/Hoth/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 1,
	"Rarity": 5,
	"Criticism": 1,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Jakku",
	"Region": "Inner Rim",
	"Sector": "Jakku's",
	"System": "Jakku",
	"Inhabitants": "Teedo, Uthuthma",
	"Starport": 0,
	"Capital City": "Niima Outpost",
	"Map": "I-13",
	"Climate": "arid",
	"Atmosphere": "Type I",
	"Precipitation": -5,
	"Terrain": "desert",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Jakku",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 4,
	"Criticism": -1,
	"WeaponSmall": 3,
	"WeaponRifle": 2,
	"WeaponHeavy": 1,
	"ArmorLight": 2,
	"ArmorPower": 1,
	"Slavery": 1,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Jestefad",
	"Region": "Outer Rim",
	"Sector": "Atravis",
	"System": "Mustafar",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "L-19",
	"Climate": "gas giant",
	"Atmosphere": "Type IV",
	"Precipitation": 2,
	"Terrain": "gas giant",
	"Gravity": 1.1,
	"URL": "https://starwars.fandom.com/wiki/Jestefad/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -99,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Kadavo",
	"Region": "Wild Space",
	"Sector": "Unknown",
	"System": "Kadavo",
	"Inhabitants": "Zygerrians",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Unknown",
	"Climate": "frigid",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "volcanic",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Kadavo/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 5,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Kamino",
	"Region": "Wild Space",
	"Sector": "Abrion",
	"System": "Kamino",
	"Inhabitants": "Kaminoans",
	"Starport": 0,
	"Capital City": "Tipoca City",
	"Map": "Unknown",
	"Climate": "cold",
	"Atmosphere": "Type I",
	"Precipitation": 4,
	"Terrain": "ocean",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Kamino",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Kashyyyk",
	"Region": "Mid Rim",
	"Sector": "Mytaranor",
	"System": "Kashyyyk",
	"Inhabitants": "Wookiees",
	"Starport": 0,
	"Capital City": "Kachirho",
	"Map": "P-9",
	"Climate": "tropical",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "immense jungles and forest",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Kashyyyk/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Kessel",
	"Region": "Outer Rim",
	"Sector": "Kessel",
	"System": "Kessel",
	"Inhabitants": "Various",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "T-10",
	"Climate": "cold,dry",
	"Atmosphere": "Type III, thin",
	"Precipitation": 3,
	"Terrain": "alkali flat,barren rocky mountain",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Kessel/Legends",
	"ImperialPresence": 0,
	"OldWestiness": -3,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 5,
	"DroidsRestricted": -1,
	"DroidsFree": -3,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Kijimi",
	"Region": "Mid Rim",
	"Sector": "Bryx",
	"System": "Kijimi",
	"Inhabitants": "Human, Anzellan, Boosodian, Melitto",
	"Starport": 0,
	"Capital City": "Kijimi City",
	"Map": "R-8",
	"Climate": "frigid",
	"Atmosphere": "Type I",
	"Precipitation": 1,
	"Terrain": "mountain",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Kijimi",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Kintan",
	"Region": "Outer Rim",
	"Sector": "Si'Klaata Cluster",
	"System": "Unknown",
	"Inhabitants": "Nikto",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "S-9",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "rocky wasteland,archipelago,forest,swamp,magma",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Kintan/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 4,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Kirtarkin",
	"Region": "Outer Rim",
	"Sector": "Anoat",
	"System": "Kirtarkin",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Unknown",
	"Climate": "temperate",
	"Atmosphere": "Type II",
	"Precipitation": 1,
	"Terrain": "polluted urban",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Kirtarkin/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Klatooine",
	"Region": "Hutt Space",
	"Sector": "Si'Klaata Cluster",
	"System": "Klatooine",
	"Inhabitants": "Klatooinians",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "S-9",
	"Climate": "arid",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "desert,savannah",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Klatooine/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 3,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Lowick",
	"Region": "Outer Rim",
	"Sector": "Calaron",
	"System": "Pa'Lowick",
	"Inhabitants": "Pa'lowick, Gorach",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "U-9",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "mountain,ocean,rainforest,salt marsh,sea",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Lowick/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Malador",
	"Region": "Mid Rim",
	"Sector": "Senex",
	"System": "Malador",
	"Inhabitants": "Various",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "L-17",
	"Climate": "smoggy",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "urban",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Malador/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 2,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Malastare",
	"Region": "Mid Rim",
	"Sector": "Dustig",
	"System": "Malastare",
	"Inhabitants": "Dugs",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "N-16",
	"Climate": "arid,temperate,tropical",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "desert,jungle,methane lake",
	"Gravity": 1.56,
	"URL": "https://starwars.fandom.com/wiki/Malastare/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 3,
	"Criticism": 5,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Manaan",
	"Region": "Inner Rim",
	"Sector": "Manaan",
	"System": "Pyrshak",
	"Inhabitants": "Selkath",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "O-11",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "locationwide ocean,island",
	"Gravity": 1.3,
	"URL": "https://starwars.fandom.com/wiki/Manaan/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Mandalore",
	"Region": "Outer Rim",
	"Sector": "Mandalore",
	"System": "Mandalore",
	"Inhabitants": "Alamite, Humans",
	"Starport": 0,
	"Capital City": "Keldabe (formerly), Sundari",
	"Map": "O-7",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "desert,forest,grassland,jungle,sea",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Mandalore/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 5,
	"WeaponRifle": 5,
	"WeaponHeavy": 5,
	"ArmorLight": 5,
	"ArmorPower": 5,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Mataou",
	"Region": "Outer Rim",
	"Sector": "Anoat",
	"System": "Mataou",
	"Inhabitants": "Hutts",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "K-18",
	"Climate": "hot",
	"Atmosphere": "Type I",
	"Precipitation": -3,
	"Terrain": "desert",
	"Gravity": 1.1,
	"URL": "https://starwars.fandom.com/wiki/Mataou/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Megalox Beta",
	"Region": "Expansion Region",
	"Sector": "Bes Ber Bikade",
	"System": "Megalox",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "L-15",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": -5,
	"Terrain": "gravity shielded fortress",
	"Gravity": 10,
	"URL": "https://starwars.fandom.com/wiki/Megalox_Beta",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": -1,
	"DroidsRestricted": -2,
	"DroidsFree": -4,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Merj",
	"Region": "Outer Rim",
	"Sector": "Thesme",
	"System": "Merj",
	"Inhabitants": "Morseerians",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "O-6",
	"Climate": "temperate",
	"Atmosphere": "Type II",
	"Precipitation": 0,
	"Terrain": "(unknown)",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Merj",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Mustafar",
	"Region": "Outer Rim",
	"Sector": "Atravis",
	"System": "Mustafar",
	"Inhabitants": "Mustafarians",
	"Starport": 0,
	"Capital City": "Fralideja",
	"Map": "L-19",
	"Climate": "hot,ashy,stormy",
	"Atmosphere": "Type II",
	"Precipitation": 3,
	"Terrain": "cave,forest,glen,lava seas/rivers/pit,molten rock plains,obsidian mountain,volcanic",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Mustafar",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -4,
	"Criticism": 3,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Neftali",
	"Region": "Outer Rim",
	"Sector": "Kibilini",
	"System": "Socorro",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Unknown",
	"Climate": "frigid",
	"Atmosphere": "Type I",
	"Precipitation": 4,
	"Terrain": "barren glacier,fjord,frozen ocean,mountain,ice canyon",
	"Gravity": 0.09,
	"URL": "https://starwars.fandom.com/wiki/Neftali/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Neimoidia",
	"Region": "Colonies",
	"Sector": "Neimoidia",
	"System": "Neimoidia",
	"Inhabitants": "Neimoidians",
	"Starport": 0,
	"Capital City": "Koto-Si",
	"Map": "N-10",
	"Climate": "humid",
	"Atmosphere": "Type I",
	"Precipitation": 1,
	"Terrain": "desert,field,rainforest",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Neimoidia/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Nelvaan",
	"Region": "Outer Rim",
	"Sector": "Savareen",
	"System": "Koobi",
	"Inhabitants": "Nelvaanians",
	"Starport": 0,
	"Capital City": "Rokrul",
	"Map": "Q-16",
	"Climate": "frigid",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "mesa,mountain,river,forest,glacier,primitive village",
	"Gravity": 0.85,
	"URL": "https://starwars.fandom.com/wiki/Nelvaan/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Nixus",
	"Region": "Outer Rim",
	"Sector": "Dalnan",
	"System": "Haileap",
	"Inhabitants": "Aqualish, Rodian, Ugnaught",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "P-18",
	"Climate": "frigid",
	"Atmosphere": "Type I",
	"Precipitation": 1,
	"Terrain": "glacier",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Nixus",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Ord Pardron",
	"Region": "Mid Rim",
	"Sector": "Dufilvian",
	"System": "Ord Pardron",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "R-15",
	"Climate": "cool",
	"Atmosphere": "none",
	"Precipitation": 0,
	"Terrain": "barren",
	"Gravity": 0.15,
	"URL": "https://starwars.fandom.com/wiki/Ord_Pardron/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Phatrong",
	"Region": "Outer Rim",
	"Sector": "Thrasybule",
	"System": "Phatrong",
	"Inhabitants": "Kyuzos",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "P-6",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "canyon,fjord,hill,mountain,ocean,plains",
	"Gravity": 1.1,
	"URL": "https://starwars.fandom.com/wiki/Phatrong",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Polis Massa",
	"Region": "Outer Rim",
	"Sector": "Subterrel",
	"System": "Polis Massa",
	"Inhabitants": "Eellayin, Kallidahins",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "K-20",
	"Climate": "arid,none",
	"Atmosphere": "Type IV",
	"Precipitation": 1,
	"Terrain": "asteroid,rocky",
	"Gravity": 0.56,
	"URL": "https://starwars.fandom.com/wiki/Polis_Massa",
	"ImperialPresence": -5,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": -5,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Qualai",
	"Region": "Outer Rim",
	"Sector": "Kallea",
	"System": "Qualai",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "K-21",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "terrestrial",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Qualai",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Quarzite (subterranean)",
	"Region": "Inner Rim",
	"Sector": "Quartzite",
	"System": "Quarzite",
	"Inhabitants": "Belugans, Kage",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "M-13",
	"Climate": "cool",
	"Atmosphere": "Type I",
	"Precipitation": -5,
	"Terrain": "crystal cavern",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Quarzite",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Quarzite (surface)",
	"Region": "Inner Rim",
	"Sector": "Quartzite",
	"System": "Quarzite",
	"Inhabitants": "Belugans, Kage",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "M-13",
	"Climate": "cool",
	"Atmosphere": "Type IV",
	"Precipitation": 1,
	"Terrain": "pressurized surface",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Quarzite",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Radhii",
	"Region": "Wild Space",
	"Sector": "Unknown",
	"System": "Radhii",
	"Inhabitants": "Cereans, Humans",
	"Starport": 0,
	"Capital City": "Tavuu",
	"Map": "I-18",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "canyon,jungle",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Radhii",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Raxus Prime",
	"Region": "Outer Rim",
	"Sector": "Tion Hegemony",
	"System": "Raxus",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "S-5",
	"Climate": "temperate,poisonous",
	"Atmosphere": "Type I",
	"Precipitation": -1,
	"Terrain": "industrial metal junkscape,toxic waste pool",
	"Gravity": 1.2,
	"URL": "https://starwars.fandom.com/wiki/Raxus_Prime/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Riflor",
	"Region": "Mid Rim",
	"Sector": "Narrant",
	"System": "Riflorii",
	"Inhabitants": "Advozse",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "J-16",
	"Climate": "artic,frigid,cold,cool,temperate",
	"Atmosphere": "Type I",
	"Precipitation": -3,
	"Terrain": "fluctuating gravity,volcanic mountain,forest,jungle",
	"Gravity": 1.4,
	"URL": "https://starwars.fandom.com/wiki/Riflor/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -4,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Rodia",
	"Region": "Outer Rim",
	"Sector": "Savareen",
	"System": "Tyrius",
	"Inhabitants": "Rodians",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "R-16",
	"Climate": "hot,humid",
	"Atmosphere": "Type I",
	"Precipitation": 5,
	"Terrain": "jungle,swamp,ocean",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Rodia",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Ryloth",
	"Region": "Outer Rim",
	"Sector": "Gaulus",
	"System": "Ryloth",
	"Inhabitants": "Twi'leks",
	"Starport": 0,
	"Capital City": "Lessu",
	"Map": "R-17",
	"Climate": "hot,humid",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "desert,dense jungle,mesa,valley,volcanic",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Ryloth",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 5,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Sarka",
	"Region": "Mid Rim",
	"Sector": "Sarka",
	"System": "Sarka",
	"Inhabitants": "Sarkans",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Q-8",
	"Climate": "hot",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "jungle,marshland,cave",
	"Gravity": 1.3,
	"URL": "https://starwars.fandom.com/wiki/Sarka/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Sevarcos II",
	"Region": "Outer Rim",
	"Sector": "Tamarin",
	"System": "Sevarcos",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "N-19",
	"Climate": "arid",
	"Atmosphere": "Type II",
	"Precipitation": -4,
	"Terrain": "mountain,plains,desert,tunnel,underground water",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Sevarcos_II",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 3,
	"Criticism": 1,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Sirpar",
	"Region": "Outer Rim",
	"Sector": "Arkanis",
	"System": "Sirpar",
	"Inhabitants": "Humans",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Unknown",
	"Climate": "hot",
	"Atmosphere": "Type I",
	"Precipitation": -3,
	"Terrain": "jungle,desert,mountain",
	"Gravity": 1.1,
	"URL": "https://starwars.fandom.com/wiki/Sirpar/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 1,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Skako",
	"Region": "Core Worlds",
	"Sector": "Skako",
	"System": "Skako",
	"Inhabitants": "Skakoans",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "L-9",
	"Climate": "temperate with high pressure",
	"Atmosphere": "Type IV",
	"Precipitation": 1,
	"Terrain": "urban,vine",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Skako/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -4,
	"Criticism": 4,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Skor II",
	"Region": "Outer Rim",
	"Sector": "Airam",
	"System": "Squab",
	"Inhabitants": "Squib",
	"Starport": 0,
	"Capital City": "Metrobig",
	"Map": "M-20",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "bluff,canyon,cave,cavern,city,desert,flatland,forest,grassland,hill,ice canyon,ice cap,ice cave,ice grotto,ice plains,industrial,island,isolated forest,jungle,lake,marshland,mesa,mountain,ocean,plains,plateau,primitive village,rainforest,river,rocky,salt marsh,saltwater ocean,savannah,sea,snowfield,swamp,tundra,urban,valley,village,volcanic,wasteland,woodland,",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Skor_II",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 1,
	"Criticism": -1,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Subterrel",
	"Region": "Outer Rim",
	"Sector": "Subterrel",
	"System": "Subterrel",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "L-20",
	"Climate": "acid fog",
	"Atmosphere": "Type II",
	"Precipitation": -5,
	"Terrain": "cave",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Subterrel/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 1,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Sullust",
	"Region": "Outer Rim",
	"Sector": "Sullust",
	"System": "Sullust",
	"Inhabitants": "Sullustans",
	"Starport": 0,
	"Capital City": "Pinyumb",
	"Map": "M-17",
	"Climate": "hot",
	"Atmosphere": "Type II",
	"Precipitation": 1,
	"Terrain": "volcanic,molten",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Sullust",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Sump",
	"Region": "Outer Rim",
	"Sector": "Koradin",
	"System": "Sump",
	"Inhabitants": "Nuknog",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "I-18",
	"Climate": "polluted",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "toxic marsh,urban",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Sump/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 2,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Taloraan",
	"Region": "Expansion Region",
	"Sector": "Freestanding Subsectors",
	"System": "Kelavine",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Unknown",
	"Climate": "hot",
	"Atmosphere": "Type IV",
	"Precipitation": 5,
	"Terrain": "cloudscape",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Taloraan/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -99,
	"Criticism": 1,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Tansyl 5",
	"Region": "Mid Rim",
	"Sector": "Iskin",
	"System": "Tansyl",
	"Inhabitants": "Frigosian",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "O-16",
	"Climate": "temperate",
	"Atmosphere": "Type II",
	"Precipitation": 0,
	"Terrain": "(unknown)",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Tansyl_5",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Tatooine",
	"Region": "Outer Rim",
	"Sector": "Arkanis",
	"System": "Tatoo",
	"Inhabitants": "Jawas, Tusken Raiders",
	"Starport": 0,
	"Capital City": "Bestine",
	"Map": "R-16",
	"Climate": "hot,arid",
	"Atmosphere": "Type I",
	"Precipitation": -5,
	"Terrain": "canyon,desert,mountain,bluff",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Tatooine",
	"ImperialPresence": 0,
	"OldWestiness": 1,
	"Megafauna": 1,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 4,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Tei-Untis",
	"Region": "Core Worlds",
	"Sector": "The Interior",
	"System": "Tei-Untis",
	"Inhabitants": "Zabraks",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "K-10",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "city",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Tei-Untis",
	"ImperialPresence": 0,
	"OldWestiness": 5,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Tokmia",
	"Region": "Outer Rim",
	"Sector": "Anoat",
	"System": "Tokmia",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Unknown",
	"Climate": "frigid",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "forest,snowfield",
	"Gravity": 0.09,
	"URL": "https://starwars.fandom.com/wiki/Tokmia/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Trandosha",
	"Region": "Mid Rim",
	"Sector": "Mytaranor",
	"System": "Kashyyyk",
	"Inhabitants": "Trandoshans",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "P-9",
	"Climate": "humid,arid",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "jungle,rainforest,woodland,savannah,desert,grassland,high mountain,sea,village",
	"Gravity": 0.62,
	"URL": "https://starwars.fandom.com/wiki/Trandosha/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Tyegin",
	"Region": "Inner Rim",
	"Sector": "Tyegin",
	"System": "Tyegin",
	"Inhabitants": "Humans, Feeorin, Fosh. Tarsunt",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "O-10",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "forest,railroad",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Tyegin",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Ukio",
	"Region": "Outer Rim",
	"Sector": "Abrion",
	"System": "Ukio",
	"Inhabitants": "Ukians",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "S-15",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 1,
	"Terrain": "plains",
	"Gravity": 0.8,
	"URL": "https://starwars.fandom.com/wiki/Ukio/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Unidentified location (Ilum system)",
	"Region": "Unknown Regions",
	"Sector": "7G",
	"System": "Ilum",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Unknown",
	"Climate": "none",
	"Atmosphere": "none",
	"Precipitation": 3,
	"Terrain": "rock",
	"Gravity": 0.1,
	"URL": "https://starwars.fandom.com/wiki/Unidentified_location_(Ilum_system)",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Veelo",
	"Region": "Outer Rim",
	"Sector": "Veelo",
	"System": "Veelo",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Unknown",
	"Climate": "temperate",
	"Atmosphere": "Type III",
	"Precipitation": 2,
	"Terrain": "swamp,waterland",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Veelo",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -3,
	"Criticism": 3,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Vodran",
	"Region": "Hutt Space",
	"Sector": "Si'Klaata Cluster",
	"System": "Vodran",
	"Inhabitants": "Vodrans, Hutts",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "S-9",
	"Climate": "murky,humid",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "jungle,rainforest,swamp",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Vodran/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 5,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Yaga Minor",
	"Region": "Outer Rim",
	"Sector": "Prefsbelt",
	"System": "Yaga Minor",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "K-5",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "cave,forest,mountain",
	"Gravity": 1.2,
	"URL": "https://starwars.fandom.com/wiki/Yaga_Minor/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -3,
	"Criticism": 4,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": -5,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Yar Togna",
	"Region": "Outer Rim",
	"Sector": "Sarin",
	"System": "Yar Togna",
	"Inhabitants": "Tognath",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "P-18",
	"Climate": "low-oxygen atmosphere",
	"Atmosphere": "Type I",
	"Precipitation": -1,
	"Terrain": "flatland,volcanic mountain",
	"Gravity": 1.1,
	"URL": "https://starwars.fandom.com/wiki/Yar_Togna",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 5,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Yavin Prime",
	"Region": "Outer Rim",
	"Sector": "Gordian Reach",
	"System": "Yavin",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "P-6",
	"Climate": "hostile; chemical and magnetic storms",
	"Atmosphere": "Type IV",
	"Precipitation": 3,
	"Terrain": "gas giant",
	"Gravity": 4,
	"URL": "https://starwars.fandom.com/wiki/Yavin_Prime/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Ylesia",
	"Region": "Hutt Space",
	"Sector": "Unknown",
	"System": "Cha Raaba",
	"Inhabitants": "Human, Hutt, Yuuzhan Vong, others",
	"Starport": 0,
	"Capital City": "Peace City",
	"Map": "T-12",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "island,jungle,mountain",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Ylesia/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 4,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Zygerria",
	"Region": "Outer Rim",
	"Sector": "Chorlian",
	"System": "Zygerria",
	"Inhabitants": "Zygerrians",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "S-4",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "plains,mesa,highland",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Zygerria/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 5,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "generic Colonies location",
	"Region": "Colonies",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "I-11",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Colonies/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "generic Core Worlds location",
	"Region": "Core Worlds",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "J-11",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Core_Worlds/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "generic Deep Core location",
	"Region": "Deep Core",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "L-11",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Deep_Core/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "generic Expansion Region location",
	"Region": "Expansion Region",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "H-11",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Expansion_Region/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "generic Extragalactic location",
	"Region": "Extragalactic",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "U-20",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Extragalactic/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "generic Hutt Space location",
	"Region": "Hutt Space",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "T-11",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Hutt_Space/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "generic Inner Rim location",
	"Region": "Inner Rim",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "I-12",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Inner_Rim/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "generic Mid Rim location",
	"Region": "Mid Rim",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "H-11",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Mid_Rim/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "generic Outer Rim location",
	"Region": "Outer Rim",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Q-19",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Outer_Rim_Territories/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "generic Unknown Regions location",
	"Region": "Unknown Regions",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "G-11",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Unknown_Regions/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "generic Unknown location",
	"Region": "Unknown",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "Unknown",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "(unknown)",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "generic Wild Space location",
	"Region": "Wild Space",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"Capital City": "Unknown",
	"Map": "F-18",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Wild_Space/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
}
];


const regions = [
{
	"Name": "Deep Core",
	"ImperialPresence": 5,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 3,
	"Criticism": -3,
	"WeaponSmall": -1,
	"WeaponRifle": -2,
	"WeaponHeavy": -3,
	"ArmorLight": -2,
	"ArmorPower": -3,
	"Slavery": 1,
	"DroidsRestricted": 5,
	"DroidsFree": 4,
	"Cybernetics": 3,
	"Spice": -3,
	"Drugs": -3,
	"Ores": 0,
	"Trespassing": -2,
	"Poison": 0,
	"Military": -3,
	"Slicing": -3,
	"Theft": -2,
	"Bribery": -3,
	"Livestock": -4,
	"Vehicles": 0,
	"RidingBeasts": -1
},
{
	"Name": "Core Worlds",
	"ImperialPresence": 5,
	"OldWestiness": 0,
	"Megafauna": -5,
	"Rarity": -1,
	"Criticism": -3,
	"WeaponSmall": -1,
	"WeaponRifle": -2,
	"WeaponHeavy": -3,
	"ArmorLight": -2,
	"ArmorPower": -3,
	"Slavery": -1,
	"DroidsRestricted": 5,
	"DroidsFree": 4,
	"Cybernetics": 4,
	"Spice": -1,
	"Drugs": -2,
	"Ores": 0,
	"Trespassing": -1,
	"Poison": 0,
	"Military": -3,
	"Slicing": -1,
	"Theft": -1,
	"Bribery": 0,
	"Livestock": -2,
	"Vehicles": 5,
	"RidingBeasts": -2
},
{
	"Name": "Colonies",
	"ImperialPresence": 5,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": -2,
	"WeaponSmall": -2,
	"WeaponRifle": -3,
	"WeaponHeavy": -4,
	"ArmorLight": -3,
	"ArmorPower": -4,
	"Slavery": -2,
	"DroidsRestricted": 5,
	"DroidsFree": 4,
	"Cybernetics": 1,
	"Spice": 4,
	"Drugs": 2,
	"Ores": -1,
	"Trespassing": -2,
	"Poison": 0,
	"Military": -5,
	"Slicing": 0,
	"Theft": -1,
	"Bribery": 1,
	"Livestock": -1,
	"Vehicles": 1,
	"RidingBeasts": -1
},
{
	"Name": "Inner Rim",
	"ImperialPresence": 4,
	"OldWestiness": 0,
	"Megafauna": -4,
	"Rarity": 0,
	"Criticism": -1,
	"WeaponSmall": 1,
	"WeaponRifle": 0,
	"WeaponHeavy": -1,
	"ArmorLight": 1,
	"ArmorPower": 0,
	"Slavery": -1,
	"DroidsRestricted": 4,
	"DroidsFree": 3,
	"Cybernetics": 0,
	"Spice": 2,
	"Drugs": 1,
	"Ores": 0,
	"Trespassing": -1,
	"Poison": -1,
	"Military": -3,
	"Slicing": -2,
	"Theft": -3,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Expansion Region",
	"ImperialPresence": 3,
	"OldWestiness": 0,
	"Megafauna": -3,
	"Rarity": 0,
	"Criticism": 0,
	"WeaponSmall": 2,
	"WeaponRifle": 1,
	"WeaponHeavy": 0,
	"ArmorLight": 1,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 3,
	"DroidsFree": 2,
	"Cybernetics": 1,
	"Spice": 3,
	"Drugs": 1,
	"Ores": 1,
	"Trespassing": -1,
	"Poison": 0,
	"Military": -3,
	"Slicing": -1,
	"Theft": -1,
	"Bribery": 0,
	"Livestock": -1,
	"Vehicles": 0,
	"RidingBeasts": 1
},
{
	"Name": "Mid Rim",
	"ImperialPresence": 2,
	"OldWestiness": 0,
	"Megafauna": -2,
	"Rarity": 1,
	"Criticism": 1,
	"WeaponSmall": 3,
	"WeaponRifle": 2,
	"WeaponHeavy": 1,
	"ArmorLight": 2,
	"ArmorPower": 1,
	"Slavery": 1,
	"DroidsRestricted": 1,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 4,
	"Drugs": 3,
	"Ores": 2,
	"Trespassing": -1,
	"Poison": 0,
	"Military": -3,
	"Slicing": -1,
	"Theft": -1,
	"Bribery": 0,
	"Livestock": -1,
	"Vehicles": 0,
	"RidingBeasts": 2
},
{
	"Name": "Outer Rim",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 2,
	"Criticism": 2,
	"WeaponSmall": 4,
	"WeaponRifle": 3,
	"WeaponHeavy": 2,
	"ArmorLight": 3,
	"ArmorPower": 2,
	"Slavery": 2,
	"DroidsRestricted": 2,
	"DroidsFree": 1,
	"Cybernetics": -1,
	"Spice": 5,
	"Drugs": 4,
	"Ores": 4,
	"Trespassing": 1,
	"Poison": 1,
	"Military": -1,
	"Slicing": 0,
	"Theft": -1,
	"Bribery": 1,
	"Livestock": 3,
	"Vehicles": 0,
	"RidingBeasts": 3
},
{
	"Name": "Wild Space",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 5,
	"Rarity": 3,
	"Criticism": 3,
	"WeaponSmall": 5,
	"WeaponRifle": 4,
	"WeaponHeavy": 3,
	"ArmorLight": 4,
	"ArmorPower": 3,
	"Slavery": 2,
	"DroidsRestricted": 5,
	"DroidsFree": 5,
	"Cybernetics": 5,
	"Spice": 4,
	"Drugs": 3,
	"Ores": 5,
	"Trespassing": 5,
	"Poison": 5,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 5,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Hutt Space",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 4,
	"Rarity": 2,
	"Criticism": 4,
	"WeaponSmall": 5,
	"WeaponRifle": 5,
	"WeaponHeavy": 4,
	"ArmorLight": 5,
	"ArmorPower": 4,
	"Slavery": 5,
	"DroidsRestricted": 5,
	"DroidsFree": 4,
	"Cybernetics": 2,
	"Spice": 5,
	"Drugs": 3,
	"Ores": 3,
	"Trespassing": 3,
	"Poison": -1,
	"Military": -4,
	"Slicing": 1,
	"Theft": 1,
	"Bribery": 2,
	"Livestock": 4,
	"Vehicles": 1,
	"RidingBeasts": 4
},
{
	"Name": "Unknown Regions",
	"ImperialPresence": -5,
	"OldWestiness": 0,
	"Megafauna": 5,
	"Rarity": 5,
	"Criticism": 5,
	"WeaponSmall": 5,
	"WeaponRifle": 5,
	"WeaponHeavy": 5,
	"ArmorLight": 5,
	"ArmorPower": 5,
	"Slavery": 5,
	"DroidsRestricted": 5,
	"DroidsFree": 5,
	"Cybernetics": 5,
	"Spice": 5,
	"Drugs": 5,
	"Ores": 5,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
},
{
	"Name": "Unknown",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 5,
	"Criticism": 5,
	"WeaponSmall": 0,
	"WeaponRifle": 0,
	"WeaponHeavy": 0,
	"ArmorLight": 0,
	"ArmorPower": 0,
	"Slavery": 0,
	"DroidsRestricted": 0,
	"DroidsFree": 0,
	"Cybernetics": 0,
	"Spice": 0,
	"Drugs": 0,
	"Ores": 0,
	"Trespassing": 0,
	"Poison": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
	"Livestock": 0,
	"Vehicles": 0,
	"RidingBeasts": 0
}
];
