// JSON list of locations
const locations = [
{
	"Name": "Alderaan",
	"Region": "Core Worlds",
	"Sector": "Alderaan",
	"System": "Alderaan",
	"Inhabitants": "Humans (Alderaanian)",
	"Starport": 4,
	"CapitalCity": "Aldera",
	"Map": "M-10",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "forest,mountain,plains",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Alderaan",
	"ImperialPresence": 4,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Aleen (surface)",
	"Region": "Mid Rim",
	"Sector": "Bright Jewel",
	"System": "Aleen",
	"Inhabitants": "Aleena",
	"Starport": 3,
	"CapitalCity": "(none)",
	"Map": "L-7",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": -4,
	"Terrain": "rocky mesa,desert plains,isolated forest",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Aleen/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Aleen (underground)",
	"Region": "Mid Rim",
	"Sector": "Bright Jewel",
	"System": "Aleen",
	"Inhabitants": "Kindalo",
	"Starport": 3,
	"CapitalCity": "(none)",
	"Map": "L-7",
	"Climate": "temperate",
	"Atmosphere": "Type II",
	"Precipitation": -5,
	"Terrain": "cavern,luminescent vegetation grove",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Aleen/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Aloxl",
	"Region": "Deep Core",
	"Sector": "Deep Core",
	"System": "Aloxl",
	"Inhabitants": "(none)",
	"Starport": 3,
	"CapitalCity": "(none)",
	"Map": "L-10",
	"Climate": "hot",
	"Atmosphere": "Type IV",
	"Precipitation": -3,
	"Terrain": "arid plains,extreme heat during hot cycle",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Aloxl/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Ando",
	"Region": "Mid Rim",
	"Sector": "Lambda",
	"System": "Ando",
	"Inhabitants": "Aqualish",
	"Starport": 4,
	"CapitalCity": "Quantill City",
	"Map": "Q-15",
	"Climate": "temperate,humid",
	"Atmosphere": "Type I",
	"Precipitation": 4,
	"Terrain": "cave,rainforest,saltwater ocean,swamp,small rocky island",
	"Gravity": 1.22,
	"URL": "https://starwars.fandom.com/wiki/Ando/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Anoat",
	"Region": "Outer Rim",
	"Sector": "Anoat",
	"System": "Anoat",
	"Inhabitants": "Humans,Ugnaughts",
	"Starport": 3,
	"CapitalCity": "Anoat City",
	"Map": "K-18",
	"Climate": "hot",
	"Atmosphere": "Type II",
	"Precipitation": 0,
	"Terrain": "polluted sludge",
	"Gravity": 0.85,
	"URL": "https://starwars.fandom.com/wiki/Anoat/Legends",
	"ImperialPresence": 1,
	"OldWestiness": -1,
	"Megafauna": -1,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Ansion",
	"Region": "Mid Rim",
	"Sector": "Churnis",
	"System": "Ansion",
	"Inhabitants": "Ansionian,Gwurran,Armalat,Humans,Hutts",
	"Starport": 3,
	"CapitalCity": "Cuipernam",
	"Map": "I-6",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "grassland,hill,plateau",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Ansion/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Arbra",
	"Region": "Outer Rim",
	"Sector": "Bon'nyuw-Luq",
	"System": "Arbra",
	"Inhabitants": "Arbrans,Hoojibs",
	"Starport": 3,
	"CapitalCity": "Gotto City",
	"Map": "N-17",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "rainforest,jungle,mountain,cave,ice cap,small sea,volcanic",
	"Gravity": 0.97,
	"URL": "https://starwars.fandom.com/wiki/Arbra/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Atraken",
	"Region": "Outer Rim",
	"Sector": "Rolion",
	"System": "Atraken",
	"Inhabitants": "Ee,Humans,Cidwen",
	"Starport": 3,
	"CapitalCity": "Katellyn City",
	"Map": "Q-7",
	"Climate": "cool",
	"Atmosphere": "Type III",
	"Precipitation": 1,
	"Terrain": "cave,crater,mountain,ocean,poisonous water",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Atraken/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Auratera",
	"Region": "Outer Rim",
	"Sector": "Vorzyd",
	"System": "Auratera",
	"Inhabitants": "Duros,Humans,Ithorians,Iktotchi,Twi'leks",
	"Starport": 3,
	"CapitalCity": "Senoloro,Dewbright,Hriin",
	"Map": "R-6",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "mountain,forest,plains",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Auratera/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Bakura",
	"Region": "Wild Space",
	"Sector": "Bakura",
	"System": "Bakura",
	"Inhabitants": "Kurtzen",
	"Starport": 3,
	"CapitalCity": "Salis D'aar",
	"Map": "G-16",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "forest,plains,mountain,small sea,river,valley",
	"Gravity": 1.05,
	"URL": "https://starwars.fandom.com/wiki/Bakura/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Bardotta",
	"Region": "Colonies",
	"Sector": "Shasos",
	"System": "Bardotta",
	"Inhabitants": "Bardottans",
	"Starport": 4,
	"CapitalCity": "Bardotta Capital City",
	"Map": "K-13",
	"Climate": "cold",
	"Atmosphere": "Type I",
	"Precipitation": 1,
	"Terrain": "mountain,highland,plains,ice cap",
	"Gravity": 0.95,
	"URL": "https://starwars.fandom.com/wiki/Bardotta",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Bespin",
	"Region": "Outer Rim",
	"Sector": "Anoat",
	"System": "Bespin",
	"Inhabitants": "Neo-Bespinian,Tibannuck,Humans,Lutrillians,Sullustans,Ugnaughts",
	"Starport": 3,
	"CapitalCity": "Cloud City",
	"Map": "K-18",
	"Climate": "temperate and normal gravity in the Life Zone",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "gas giant,cloudscape",
	"Gravity": 1.5,
	"URL": "https://starwars.fandom.com/wiki/Bespin/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Bothawui",
	"Region": "Mid Rim",
	"Sector": "Bothan Space",
	"System": "Both",
	"Inhabitants": "Bothans",
	"Starport": 3,
	"CapitalCity": "Drev'starn",
	"Map": "R-14",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "plains,mountain,forest,urban",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Bothawui/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Byss",
	"Region": "Deep Core",
	"Sector": "Deep Core Security Zone",
	"System": "Beshqek",
	"Inhabitants": "Humans",
	"Starport": "2",
	"CapitalCity": "Emperor's Ruling City",
	"Map": "K-11",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "urban sprawl,plateau,canyon,lake",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Byss/Legends",
	"ImperialPresence": 5,
	"OldWestiness": 0,
	"Megafauna": "-5",
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 5,
	"Spice": -1,
	"Trespassing": -2,
	"Military": 3,
	"Slicing": -3,
	"Theft": -3,
	"Bribery": 0,
},
{
	"Name": "Carida",
	"Region": "Colonies",
	"Sector": "Carida",
	"System": "Carida",
	"Inhabitants": "Caridan",
	"Starport": 3,
	"CapitalCity": "Carida Academy,Imperial Navy Deepdock Facility Two,Ryleel Imperial Base,Valor",
	"Map": "M-9",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 1,
	"Terrain": "forest,desert,glacier,jungle,arctic tundra",
	"Gravity": 1.98,
	"URL": "https://starwars.fandom.com/wiki/Carida/Legends",
	"ImperialPresence": 2,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Corellia",
	"Region": "Core Worlds",
	"Sector": "Corellian",
	"System": "Corellia",
	"Inhabitants": "Humans (Corellian), Various",
	"Starport": 5,
	"CapitalCity": "Coronet City",
	"Map": "M-11",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "plains,urban,hill,forest,mesa,mountain,island,jungle",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Corellia/Legends",
	"ImperialPresence": 2, // the Five Brothers
	"OldWestiness": -2,
	"Megafauna": -5,
	"Rarity": 0,
	"Criticism": 4,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Coruscant",
	"Region": "Core Worlds",
	"Sector": "Corusca",
	"System": "Coruscant",
	"Inhabitants": "Various",
	"Starport": "5",
	"CapitalCity": "Galactic City",
	"Map": "L-9",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "ecumenopolis",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Coruscant",
	"ImperialPresence": 5,
	"OldWestiness": -2,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": -3,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Dantooine",
	"Region": "Outer Rim",
	"Sector": "Raioballo",
	"System": "Dantooine",
	"Inhabitants": "Dantari",
	"Starport": 3,
	"CapitalCity": "Garang",
	"Map": "L-4",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "ocean,savanna,mountain,steppes,rivers,grasslands",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Dantooine/Legends",
	"ImperialPresence": -3,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Dathomir",
	"Region": "Outer Rim",
	"Sector": "Quelli",
	"System": "Dathomir",
	"Inhabitants": "Fromprath (later exiled), Zabraks (Dathomirian)",
	"Starport": 3,
	"CapitalCity": "Aurilia,Blue Desert City,Howling Crag Clan Village,Nightsister Stronghold,Singing Mountain Clan Fortress",
	"Map": "O-6",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "desert,forest,jungle,mountain",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Dathomir/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Dorin",
	"Region": "Expansion Region",
	"Sector": "Deadalis",
	"System": "Dorin",
	"Inhabitants": "Kel Dor",
	"Starport": 3,
	"CapitalCity": "Dor'shan",
	"Map": "J-8",
	"Climate": "temperate,stormy",
	"Atmosphere": "Type III",
	"Precipitation": 2,
	"Terrain": "mountain,valley,plateau",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Dorin/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 1,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Duro",
	"Region": "Core Worlds",
	"Sector": "Duro",
	"System": "Duro",
	"Inhabitants": "Duros",
	"Starport": 5,
	"CapitalCity": "Bburru Station",
	"Map": "M-11",
	"Climate": "temperate",
	"Atmosphere": "Type IV",
	"Precipitation": 2,
	"Terrain": "jungle,polluted wasteland",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Duro/Legends",
	"ImperialPresence": 3,
	"OldWestiness": 3,
	"Megafauna": 1,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Endor (Gas Giant)",
	"Region": "Outer Rim",
	"Sector": "Moddell",
	"System": "Endor",
	"Inhabitants": "(none)",
	"Starport": 0,
	"CapitalCity": "(none)",
	"Map": "H-16",
	"Climate": "chemical and magnetic storms",
	"Atmosphere": "Type IV",
	"Precipitation": 5,
	"Terrain": "gas giant",
	"Gravity": 2.5,
	"URL": "https://starwars.fandom.com/wiki/Endor_(planet)/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 4,
	"Criticism": -4,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Endor (Forest Moon)",
	"Region": "Outer Rim",
	"Sector": "Moddell",
	"System": "Endor",
	"Inhabitants": "Duloks,Ewoks,Gorphs,Mimphs,Wisties,Yuzzums",
	"Starport": 2,
	"CapitalCity": "Bright Tree Village,Hanging Moss Village,Terak's Keep,Happy Grove,Red Bush Grove",
	"Map": "H-16",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "forests,mountains,deserts,savannahs,lakes,rivers,seas",
	"Gravity": 0.85,
	"URL": "https://starwars.fandom.com/wiki/Endor_(location)/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Falleen",
	"Region": "Mid Rim",
	"Sector": "Doldur",
	"System": "Falleen",
	"Inhabitants": "Falleen",
	"Starport": 3,
	"CapitalCity": "Falleen Throne",
	"Map": "P-15",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "jungle,mountain,plains,industrial",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Falleen_(location)/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Felucia",
	"Region": "Outer Rim",
	"Sector": "Thanium",
	"System": "Felucia",
	"Inhabitants": "Felucians, Jungle Felucians",
	"Starport": 3,
	"CapitalCity": "Kway Teow",
	"Map": "R-6",
	"Climate": "hot,humid",
	"Atmosphere": "Type I",
	"Precipitation": 4,
	"Terrain": "jungle,swamp",
	"Gravity": 0.75,
	"URL": "https://starwars.fandom.com/wiki/Felucia",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Gabredor III",
	"Region": "Outer Rim",
	"Sector": "Myto",
	"System": "Gabredor",
	"Inhabitants": "Defel,Human",
	"Starport": 3,
	"CapitalCity": "Gabredor III colony,Science colony",
	"Map": "K-4",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 4,
	"Terrain": "jungle",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Gabredor_III/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 5, // Karazak Slavers
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Galaan",
	"Region": "Outer Rim",
	"Sector": "Corva",
	"System": "Galaan",
	"Inhabitants": "(varied)",
	"Starport": 2,
	"CapitalCity": "New Republic Communications & Intelligence Base",
	"Map": "P-4",
	"Climate": "frigid",
	"Atmosphere": "Type IV",
	"Precipitation": 5,
	"Terrain": "gas giant",
	"Gravity": 2,
	"URL": "https://starwars.fandom.com/wiki/Galaan/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -99,
	"Criticism": -5,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Galzez",
	"Region": "Mid Rim",
	"Sector": "Dustig",
	"System": "Galzez",
	"Inhabitants": "Dugs",
	"Starport": 3,
	"CapitalCity": "Syvik Delegation base",
	"Map": "M-17",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "mountain,orange crystal",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Galzez",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Gamorr",
	"Region": "Outer Rim",
	"Sector": "Galov",
	"System": "Opoku",
	"Inhabitants": "Gamorreans",
	"Starport": 3,
	"CapitalCity": "Citadel",
	"Map": "T-14",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "forest,mountains,jungle,tundra,plains,swamp,seas",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Gamorr/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 1,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 3, // slave exports
	"Spice": 0,
	"Trespassing": 0,
	"Military": 3,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Gand",
	"Region": "Outer Rim",
	"Sector": "Shadola",
	"System": "Gand",
	"Inhabitants": "Gand",
	"Starport": 3,
	"CapitalCity": "pocket colonies,orbital space stations",
	"Map": "T-8",
	"Climate": "ammonia",
	"Atmosphere": "Type IV",
	"Precipitation": 1,
	"Terrain": "ammonia mist,rocky hill",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Gand_(location)/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -4,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Gentes",
	"Region": "Outer Rim",
	"Sector": "Anoat",
	"System": "Anoat",
	"Inhabitants": "Ugnaughts",
	"Starport": 3,
	"CapitalCity": "Sith Academy",
	"Map": "K-18",
	"Climate": "cool",
	"Atmosphere": "Type II",
	"Precipitation": -1,
	"Terrain": "wasteland",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Gentes/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 5, // Ugnaught slaves
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Geonosis",
	"Region": "Outer Rim",
	"Sector": "Arkanis",
	"System": "Geonosis",
	"Inhabitants": "Geonosians",
	"Starport": 3,
	"CapitalCity": "Stalgasin hive",
	"Map": "R-16",
	"Climate": "hot,arid",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "desert,mesa,mountain",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Geonosis",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Gravlex Med",
	"Region": "Outer Rim",
	"Sector": "Raioballo",
	"System": "Gravlex Med",
	"Inhabitants": "Anx",
	"Starport": 1,
	"CapitalCity": "Ozlyn Gox",
	"Map": "L-4",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": -1,
	"Terrain": "polluted wasteland,mountain,cave",
	"Gravity": 1.5,
	"URL": "https://starwars.fandom.com/wiki/Gravlex_Med/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Haruun Kal",
	"Region": "Mid Rim",
	"Sector": "Dustig",
	"System": "Al'Har",
	"Inhabitants": "Humans, Korun",
	"Starport": 1,
	"CapitalCity": "Pelek Baw",
	"Map": "M-17",
	"Climate": "temperate",
	"Atmosphere": "Type II",
	"Precipitation": 2,
	"Terrain": "toxic cloudsea,plateau,volcanic,jungle",
	"Gravity": 0.98,
	"URL": "https://starwars.fandom.com/wiki/Haruun_Kal/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Hoth",
	"Region": "Outer Rim",
	"Sector": "Anoat",
	"System": "Hoth",
	"Inhabitants": "Skel",
	"Starport": 3,
	"CapitalCity": "Secret Rebel Base",
	"Map": "K-18",
	"Climate": "frigid",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "canyon,frozen plains,ice cave,mountain range,tundra",
	"Gravity": 1.1,
	"URL": "https://starwars.fandom.com/wiki/Hoth/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 1,
	"Rarity": 5,
	"Criticism": 1,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Jakku",
	"Region": "Inner Rim",
	"Sector": "Jakku's",
	"System": "Jakku",
	"Inhabitants": "Teedo, Uthuthma",
	"Starport": 2,
	"CapitalCity": "Niima Outpost",
	"Map": "I-13",
	"Climate": "arid",
	"Atmosphere": "Type I",
	"Precipitation": -5,
	"Terrain": "desert",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Jakku",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 4,
	"Criticism": -1,
	"Slavery": 1,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Jestefad (Gas Giant)",
	"Region": "Outer Rim",
	"Sector": "Atravis",
	"System": "Mustafar",
	"Inhabitants": "(none)",
	"Starport": 0,
	"CapitalCity": "(none)",
	"Map": "L-19",
	"Climate": "gas giant",
	"Atmosphere": "Type IV",
	"Precipitation": 2,
	"Terrain": "gas giant",
	"Gravity": 1.1,
	"URL": "https://starwars.fandom.com/wiki/Jestefad/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -99,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Kadavo",
	"Region": "Wild Space",
	"Sector": "Chorlian",
	"System": "Kadavo",
	"Inhabitants": "Zygerrians",
	"Starport": 4,
	"CapitalCity": "Kadavo Slave Processing Facility",
	"Map": "S-4",
	"Climate": "frigid",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "volcanic",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Kadavo/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 5, // Zygerrian Slave Empire
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Kamino",
	"Region": "Wild Space",
	"Sector": "Abrion",
	"System": "Kamino",
	"Inhabitants": "Kaminoans",
	"Starport": 4,
	"CapitalCity": "Tipoca City",
	"Map": "S-15",
	"Climate": "cold",
	"Atmosphere": "Type I",
	"Precipitation": 4,
	"Terrain": "ocean",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Kamino/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Kashyyyk",
	"Region": "Mid Rim",
	"Sector": "Mytaranor",
	"System": "Kashyyyk",
	"Inhabitants": "Wookiees",
	"Starport": 4,
	"CapitalCity": "Kachirho",
	"Map": "P-9",
	"Climate": "tropical",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "immense jungles and forest",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Kashyyyk/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Kessel",
	"Region": "Outer Rim",
	"Sector": "Kessel",
	"System": "Kessel",
	"Inhabitants": "Various",
	"Starport": 4,
	"CapitalCity": "Kessendra",
	"Map": "T-10",
	"Climate": "cold,dry",
	"Atmosphere": "Type III, thin",
	"Precipitation": 3,
	"Terrain": "alkali flat,barren rocky mountain",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Kessel/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 1, // prison world
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 5, // slave labor in extensive use
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Kijimi",
	"Region": "Mid Rim",
	"Sector": "Bryx",
	"System": "Kijimi",
	"Inhabitants": "Human, Anzellan, Boosodian, Melitto",
	"Starport": 3,
	"CapitalCity": "Kijimi City",
	"Map": "R-8",
	"Climate": "frigid",
	"Atmosphere": "Type I",
	"Precipitation": 1,
	"Terrain": "mountain",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Kijimi",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Kintan",
	"Region": "Outer Rim",
	"Sector": "Si'Klaata Cluster",
	"System": "Kintan",
	"Inhabitants": "Nikto",
	"Starport": 3,
	"CapitalCity": "Fortress Kh'aris",
	"Map": "S-9",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "rocky wasteland,archipelago,forest,swamp,magma",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Kintan/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 4,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Kirtarkin",
	"Region": "Outer Rim",
	"Sector": "Anoat",
	"System": "Kirtarkin",
	"Inhabitants": "Humans,Lutrillians,Nothoiins,Mugaari",
	"Starport": 3,
	"CapitalCity": "Imperial depots",
	"Map": "K-18",
	"Climate": "temperate",
	"Atmosphere": "Type II",
	"Precipitation": 1,
	"Terrain": "polluted urban",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Kirtarkin/Legends",
	"ImperialPresence": 1, // Empire recycling centers
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Klatooine",
	"Region": "Hutt Space",
	"Sector": "Si'Klaata Cluster",
	"System": "Klatooine",
	"Inhabitants": "Klatooinians",
	"Starport": 3,
	"CapitalCity": "Treema",
	"Map": "S-9",
	"Climate": "arid",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "desert,savannah",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Klatooine/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 3,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Lowick",
	"Region": "Outer Rim",
	"Sector": "Calaron",
	"System": "Pa'Lowick",
	"Inhabitants": "Pa'lowick,Gorach",
	"Starport": 3,
	"CapitalCity": "Firegem mines",
	"Map": "U-9",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "mountain,ocean,rainforest,salt marsh,sea",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Lowick/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Malador",
	"Region": "Mid Rim",
	"Sector": "Senex",
	"System": "Malador",
	"Inhabitants": "various",
	"Starport": 4,
	"CapitalCity": "House Kellermin,abandoned factories",
	"Map": "L-17",
	"Climate": "smoggy",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "urban",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Malador/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 2,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Malastare",
	"Region": "Mid Rim",
	"Sector": "Dustig",
	"System": "Malastare",
	"Inhabitants": "Dugs,Grans,Humans",
	"Starport": 3,
	"CapitalCity": "Pixelito",
	"Map": "N-16",
	"Climate": "arid,temperate,tropical",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "desert,jungle,methane lake",
	"Gravity": 1.56,
	"URL": "https://starwars.fandom.com/wiki/Malastare/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 3,
	"Criticism": 5,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Manaan",
	"Region": "Inner Rim",
	"Sector": "Manaan",
	"System": "Pyrshak",
	"Inhabitants": "Selkath",
	"Starport": 4,
	"CapitalCity": "Ahto City",
	"Map": "O-11",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "planetwide ocean,island",
	"Gravity": 1.3,
	"URL": "https://starwars.fandom.com/wiki/Manaan/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Mandalore",
	"Region": "Outer Rim",
	"Sector": "Mandalore",
	"System": "Mandalore",
	"Inhabitants": "Alamite, Humans",
	"Starport": 5,
	"CapitalCity": "Keldabe (formerly), Sundari",
	"Map": "O-7",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "desert,forest,grassland,jungle,sea",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Mandalore/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Mataou",
	"Region": "Outer Rim",
	"Sector": "Anoat",
	"System": "Mataou",
	"Inhabitants": "Hutts",
	"Starport": 4,
	"CapitalCity": "Orbital Drydock,Mataou Fuel Station",
	"Map": "K-18",
	"Climate": "hot",
	"Atmosphere": "Type I",
	"Precipitation": -3,
	"Terrain": "desert",
	"Gravity": 1.1,
	"URL": "https://starwars.fandom.com/wiki/Mataou/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Megalox Beta",
	"Region": "Expansion Region",
	"Sector": "Bes Ber Bikade",
	"System": "Megalox",
	"Inhabitants": "(prisoners)",
	"Starport": 2,
	"CapitalCity": "Megalox Prison (surface),Megalox Space Station",
	"Map": "L-15",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": -5,
	"Terrain": "gravity shielded fortress",
	"Gravity": 10.0,
	"URL": "https://starwars.fandom.com/wiki/Megalox_Beta",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": -1,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Merj",
	"Region": "Outer Rim",
	"Sector": "Thesme",
	"System": "Merj",
	"Inhabitants": "Morseerians",
	"Starport": 3,
	"CapitalCity": "Merj Spaceport,Morseerian Laboratory Complex",
	"Map": "O-6",
	"Climate": "temperate",
	"Atmosphere": "Type II",
	"Precipitation": 0,
	"Terrain": "(unknown)",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Merj",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Mon Cala (Dac)",
	"Region": "Outer Rim",
	"Sector": "Calamari",
	"System": "Calamari",
	"Inhabitants": "Mon Calamari,Quarren,Moappa,Amphi-Hydrus,Whaladons",
	"Starport": 5,
	"CapitalCity": "Coral City,Foamwander City",
	"Map": "U-6",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "ocean,reefs,islands",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Dac/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 4,
	"Rarity": 0,
	"Criticism": 2,
	"Slavery": -1,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Mustafar",
	"Region": "Outer Rim",
	"Sector": "Atravis",
	"System": "Mustafar",
	"Inhabitants": "Mustafarians",
	"Starport": 1,
	"CapitalCity": "Fralideja",
	"Map": "L-19",
	"Climate": "hot,ashy,stormy",
	"Atmosphere": "Type II",
	"Precipitation": 3,
	"Terrain": "cave,forest,glen,lava seas/rivers/pit,molten rock plains,obsidian mountain,volcanic",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Mustafar",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -4,
	"Criticism": 3,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Neftali",
	"Region": "Outer Rim",
	"Sector": "Kibilini",
	"System": "Socorro",
	"Inhabitants": "Humans,Whiphids",
	"Starport": 3,
	"CapitalCity": "Cordel Cove",
	"Map": "Q-17",
	"Climate": "frigid",
	"Atmosphere": "Type I",
	"Precipitation": 4,
	"Terrain": "barren glacier,fjord,frozen ocean,mountain,ice canyon",
	"Gravity": 0.09,
	"URL": "https://starwars.fandom.com/wiki/Neftali/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Neimoidia",
	"Region": "Colonies",
	"Sector": "Neimoidia",
	"System": "Neimoidia",
	"Inhabitants": "Neimoidians",
	"Starport": 4,
	"CapitalCity": "Koto-Si",
	"Map": "N-10",
	"Climate": "humid",
	"Atmosphere": "Type I",
	"Precipitation": 1,
	"Terrain": "desert,field,rainforest",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Neimoidia/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Nelvaan",
	"Region": "Outer Rim",
	"Sector": "Savareen",
	"System": "Koobi",
	"Inhabitants": "Nelvaanians",
	"Starport": 3,
	"CapitalCity": "Rokrul",
	"Map": "Q-16",
	"Climate": "frigid",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "mesa,mountain,river,forest,glacier,primitive village",
	"Gravity": 0.85,
	"URL": "https://starwars.fandom.com/wiki/Nelvaan/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Nixus",
	"Region": "Outer Rim",
	"Sector": "Dalnan",
	"System": "Haileap",
	"Inhabitants": "Aqualish, Rodian, Ugnaught",
	"Starport": 3,
	"CapitalCity": "Nixus Hub 218",
	"Map": "P-18",
	"Climate": "frigid",
	"Atmosphere": "Type I",
	"Precipitation": 1,
	"Terrain": "glacier",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Nixus",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Ord Pardron",
	"Region": "Mid Rim",
	"Sector": "Dufilvian",
	"System": "Ord Pardron",
	"Inhabitants": "Humans",
	"Starport": 2,
	"CapitalCity": "Ord Pardron sector defense outpost",
	"Map": "R-15",
	"Climate": "cool",
	"Atmosphere": "none",
	"Precipitation": 0,
	"Terrain": "barren",
	"Gravity": 0.15,
	"URL": "https://starwars.fandom.com/wiki/Ord_Pardron/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Phatrong",
	"Region": "Outer Rim",
	"Sector": "Thrasybule",
	"System": "Phatrong",
	"Inhabitants": "Kyuzos",
	"Starport": 3,
	"CapitalCity": "Gorobe",
	"Map": "P-6",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "canyon,fjord,hill,mountain,ocean,plains",
	"Gravity": 1.1,
	"URL": "https://starwars.fandom.com/wiki/Phatrong",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Polis Massa",
	"Region": "Outer Rim",
	"Sector": "Subterrel",
	"System": "Polis Massa",
	"Inhabitants": "Eellayin, Kallidahins",
	"Starport": 4,
	"CapitalCity": "Polis Massa Research Base",
	"Map": "K-20",
	"Climate": "arid,none",
	"Atmosphere": "Type IV",
	"Precipitation": 1,
	"Terrain": "asteroid,rocky",
	"Gravity": 0.56,
	"URL": "https://starwars.fandom.com/wiki/Polis_Massa",
	"ImperialPresence": -5,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": -5,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Qualai",
	"Region": "Outer Rim",
	"Sector": "Kallea",
	"System": "Qualai",
	"Inhabitants": "(none)",
	"Starport": 0,
	"CapitalCity": "(none)",
	"Map": "K-21",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "terrestrial",
	"Gravity": 0.9,
	"URL": "https://starwars.fandom.com/wiki/Qualai",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Quarzite (subterranean)",
	"Region": "Inner Rim",
	"Sector": "Quartzite",
	"System": "Quarzite",
	"Inhabitants": "Belugans, Kage",
	"Starport": 0,
	"CapitalCity": "Otua Blank's fortress",
	"Map": "M-13",
	"Climate": "cool",
	"Atmosphere": "Type I",
	"Precipitation": -5,
	"Terrain": "crystal cavern",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Quarzite",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Quarzite (surface)",
	"Region": "Inner Rim",
	"Sector": "Quartzite",
	"System": "Quarzite",
	"Inhabitants": "Belugans, Kage",
	"Starport": 3,
	"CapitalCity": "Quarzite Space Station",
	"Map": "M-13",
	"Climate": "cool",
	"Atmosphere": "Type IV",
	"Precipitation": 1,
	"Terrain": "pressurized surface",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Quarzite",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Radhii",
	"Region": "Wild Space",
	"Sector": "Koradin",
	"System": "Radhii",
	"Inhabitants": "Cereans, Humans",
	"Starport": 3,
	"CapitalCity": "Tavuu",
	"Map": "I-18",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "canyon,jungle",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Radhii",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Raxus Prime",
	"Region": "Outer Rim",
	"Sector": "Tion Hegemony",
	"System": "Raxus",
	"Inhabitants": "Humans,Jawa,Rodians,Zabraks",
	"Starport": 2,
	"CapitalCity": "Central Station",
	"Map": "S-5",
	"Climate": "temperate,poisonous",
	"Atmosphere": "Type I",
	"Precipitation": -1,
	"Terrain": "industrial metal junkscape,toxic waste pool",
	"Gravity": 1.2,
	"URL": "https://starwars.fandom.com/wiki/Raxus_Prime/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Riflor",
	"Region": "Mid Rim",
	"Sector": "Narrant",
	"System": "Riflorii",
	"Inhabitants": "Advozse",
	"Starport": 3,
	"CapitalCity": "Advora",
	"Map": "J-16",
	"Climate": "artic,frigid,cold,cool,temperate",
	"Atmosphere": "Type I",
	"Precipitation": -3,
	"Terrain": "fluctuating gravity,volcanic mountain,forest,jungle",
	"Gravity": 1.4,
	"URL": "https://starwars.fandom.com/wiki/Riflor/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -4,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Rodia",
	"Region": "Outer Rim",
	"Sector": "Savareen",
	"System": "Tyrius",
	"Inhabitants": "Rodians",
	"Starport": 4,
	"CapitalCity": "Iskaayuma",
	"Map": "R-16",
	"Climate": "hot,humid",
	"Atmosphere": "Type I",
	"Precipitation": 5,
	"Terrain": "jungle,swamp,ocean",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Rodia",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Ryloth",
	"Region": "Outer Rim",
	"Sector": "Gaulus",
	"System": "Ryloth",
	"Inhabitants": "Twi'leks",
	"Starport": 4,
	"CapitalCity": "Lessu",
	"Map": "R-17",
	"Climate": "hot,humid",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "desert,dense jungle,mesa,valley,volcanic",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Ryloth",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 5,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Sarka",
	"Region": "Mid Rim",
	"Sector": "Sarka",
	"System": "Sarka",
	"Inhabitants": "Sarkans",
	"Starport": 3,
	"CapitalCity": "Salyrini",
	"Map": "Q-8",
	"Climate": "hot",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "jungle,marshland,cave",
	"Gravity": 1.3,
	"URL": "https://starwars.fandom.com/wiki/Sarka/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Sevarcos II",
	"Region": "Outer Rim",
	"Sector": "Tamarin",
	"System": "Sevarcos",
	"Inhabitants": "Humans,varied",
	"Starport": 4,
	"CapitalCity": "Imperial starports, civilian starports",
	"Map": "N-19",
	"Climate": "arid",
	"Atmosphere": "Type II",
	"Precipitation": -4,
	"Terrain": "mountain,plains,desert,tunnel,underground water",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Sevarcos_II",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 3,
	"Criticism": 1,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Sirpar",
	"Region": "Outer Rim",
	"Sector": "Arkanis",
	"System": "Sirpar",
	"Inhabitants": "Humans",
	"Starport": 3,
	"CapitalCity": "Jacelle",
	"Map": "R-17",
	"Climate": "hot",
	"Atmosphere": "Type I",
	"Precipitation": -3,
	"Terrain": "jungle,desert,mountain",
	"Gravity": 1.1,
	"URL": "https://starwars.fandom.com/wiki/Sirpar/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 1,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Skako",
	"Region": "Core Worlds",
	"Sector": "Skako",
	"System": "Skako",
	"Inhabitants": "Skakoans",
	"Starport": 3,
	"CapitalCity": "Skako (ecumenopolis)",
	"Map": "L-9",
	"Climate": "temperate with high pressure",
	"Atmosphere": "Type IV",
	"Precipitation": 1,
	"Terrain": "urban,vine",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Skako/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -4,
	"Criticism": 4,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Skor II",
	"Region": "Outer Rim",
	"Sector": "Airam",
	"System": "Squab",
	"Inhabitants": "Squib",
	"Starport": 3,
	"CapitalCity": "Metrobig",
	"Map": "M-20",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "bluff,canyon,cave,cavern,city,desert,flatland,forest,grassland,hill,ice canyon,ice cap,ice cave,ice grotto,ice plains,industrial,island,isolated forest,jungle,lake,marshland,mesa,mountain,ocean,plains,plateau,primitive village,rainforest,river,rocky,salt marsh,saltwater ocean,savannah,sea,snowfield,swamp,tundra,urban,valley,village,volcanic,wasteland,woodland,",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Skor_II",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 1,
	"Criticism": -1,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Subterrel",
	"Region": "Outer Rim",
	"Sector": "Subterrel",
	"System": "Subterrel",
	"Inhabitants": "Humans,Kallidahin,Kaminoan,Shovel-handed clone miners,varied",
	"Starport": 3,
	"CapitalCity": "(extensive mining operations)",
	"Map": "L-20",
	"Climate": "acid fog",
	"Atmosphere": "Type II",
	"Precipitation": -5,
	"Terrain": "cave",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Subterrel/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 1,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Sullust",
	"Region": "Outer Rim",
	"Sector": "Sullust",
	"System": "Sullust",
	"Inhabitants": "Sullustans",
	"Starport": 4,
	"CapitalCity": "Pinyumb",
	"Map": "M-17",
	"Climate": "hot",
	"Atmosphere": "Type II",
	"Precipitation": 1,
	"Terrain": "volcanic,molten",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Sullust",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Sump",
	"Region": "Outer Rim",
	"Sector": "Koradin",
	"System": "Sump",
	"Inhabitants": "Nuknog",
	"Starport": 2,
	"CapitalCity": "(mines,factories,port)",
	"Map": "I-18",
	"Climate": "polluted",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "toxic marsh,urban",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Sump/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 2,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Taloraan",
	"Region": "Expansion Region",
	"Sector": "Freestanding Subsectors",
	"System": "Kelavine",
	"Inhabitants": "Humans",
	"Starport": 3,
	"CapitalCity": "Taloraan City",
	"Map": "I-15",
	"Climate": "hot",
	"Atmosphere": "Type IV,Type I",
	"Precipitation": 5,
	"Terrain": "cloudscape",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Taloraan/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -99,
	"Criticism": 1,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Tansyl 5",
	"Region": "Mid Rim",
	"Sector": "Iskin",
	"System": "Tansyl",
	"Inhabitants": "Frigosian",
	"Starport": 3,
	"CapitalCity": "Tansyl 5 Capital",
	"Map": "O-16",
	"Climate": "temperate",
	"Atmosphere": "Type II",
	"Precipitation": 0,
	"Terrain": "(unknown)",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Tansyl_5",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Tatooine",
	"Region": "Outer Rim",
	"Sector": "Arkanis",
	"System": "Tatoo",
	"Inhabitants": "Jawas, Tusken Raiders",
	"Starport": 3,
	"CapitalCity": "Bestine",
	"Map": "R-16",
	"Climate": "hot,arid",
	"Atmosphere": "Type I",
	"Precipitation": -5,
	"Terrain": "canyon,desert,mountain,bluff",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Tatooine",
	"ImperialPresence": 0,
	"OldWestiness": 1,
	"Megafauna": 1,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 4,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Tei-Untis",
	"Region": "Core Worlds",
	"Sector": "The Interior",
	"System": "Tei-Untis",
	"Inhabitants": "Zabraks",
	"Starport": 3,
	"CapitalCity": "School of Ribbons",
	"Map": "K-10",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "city",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Tei-Untis",
	"ImperialPresence": 0,
	"OldWestiness": 5,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 3, // kleptocracy
	"Military": 0,
	"Slicing": 4, // kleptocracy
	"Theft": 5, // kleptocracy
	"Bribery": 4, // kleptocracy
},
{
	"Name": "Tokmia",
	"Region": "Outer Rim",
	"Sector": "Anoat",
	"System": "Tokmia",
	"Inhabitants": "Oku",
	"Starport": 0,
	"CapitalCity": "(tribal councils)",
	"Map": "K-18",
	"Climate": "frigid",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "forest,snowfield",
	"Gravity": 0.09,
	"URL": "https://starwars.fandom.com/wiki/Tokmia/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Trandosha",
	"Region": "Mid Rim",
	"Sector": "Mytaranor",
	"System": "Kashyyyk",
	"Inhabitants": "Trandoshans",
	"Starport": 4,
	"CapitalCity": "Hsskhor",
	"Map": "P-9",
	"Climate": "humid,arid",
	"Atmosphere": "Type I",
	"Precipitation": 3,
	"Terrain": "jungle,rainforest,woodland,savannah,desert,grassland,high mountain,sea,village",
	"Gravity": 0.62,
	"URL": "https://starwars.fandom.com/wiki/Trandosha/Legends",
	"ImperialPresence": 1,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Tyegin",
	"Region": "Inner Rim",
	"Sector": "Tyegin",
	"System": "Tyegin",
	"Inhabitants": "Humans, Feeorin, Fosh. Tarsunt",
	"Starport": 3,
	"CapitalCity": "(none)",
	"Map": "O-10",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "forest,railroad",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Tyegin",
	"ImperialPresence": 0,
	"OldWestiness": 1, // pirates
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Ukio",
	"Region": "Outer Rim",
	"Sector": "Abrion",
	"System": "Ukio",
	"Inhabitants": "Ukians",
	"Starport": 3,
	"CapitalCity": "Sashasa",
	"Map": "S-15",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 1,
	"Terrain": "plains",
	"Gravity": 0.8,
	"URL": "https://starwars.fandom.com/wiki/Ukio/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Veelo",
	"Region": "Outer Rim",
	"Sector": "Veelo",
	"System": "Veelo",
	"Inhabitants": "(none)",
	"Starport": 3,
	"CapitalCity": "Veelo Docks",
	"Map": "R-6",
	"Climate": "temperate",
	"Atmosphere": "Type III",
	"Precipitation": 2,
	"Terrain": "swamp,waterland",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Veelo",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": -3,
	"Criticism": 3,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Vodran",
	"Region": "Hutt Space",
	"Sector": "Si'Klaata Cluster",
	"System": "Vodran",
	"Inhabitants": "Vodrans, Hutts",
	"Starport": 3,
	"CapitalCity": "Bunku Nagara,Dekaar,Thruncan",
	"Map": "S-9",
	"Climate": "murky,humid",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "jungle,rainforest,swamp",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Vodran/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 5,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Yaga Minor",
	"Region": "Outer Rim",
	"Sector": "Prefsbelt",
	"System": "Yaga Minor",
	"Inhabitants": "Yagai",
	"Starport": 5,
	"CapitalCity": "Yavvitiri Spaceport,Preparation Center,Yaga Minor Shipyards,Ubiqtorate Base",
	"Map": "K-5",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 2,
	"Terrain": "cave,forest,mountain",
	"Gravity": 1.2,
	"URL": "https://starwars.fandom.com/wiki/Yaga_Minor/Legends",
	"ImperialPresence": 1, // Grand Moff Tarkin's base
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 5, // Yagai enslaved by Empire
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Yar Togna",
	"Region": "Outer Rim",
	"Sector": "Sarin",
	"System": "Yar Togna",
	"Inhabitants": "Tognath",
	"Starport": 3,
	"CapitalCity": "Capital City",
	"Map": "P-18",
	"Climate": "low-oxygen atmosphere",
	"Atmosphere": "Type I",
	"Precipitation": -1,
	"Terrain": "flatland,volcanic mountain",
	"Gravity": 1.1, // "high"
	"URL": "https://starwars.fandom.com/wiki/Yar_Togna",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 4, // Tognath enslaved by Empire
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 1, // Cybernetics popular
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Yavin Prime",
	"Region": "Outer Rim",
	"Sector": "Gordian Reach",
	"System": "Yavin",
	"Inhabitants": "(none)",
	"Starport": 0,
	"CapitalCity": "(none)",
	"Map": "P-6",
	"Climate": "hostile; chemical and magnetic storms",
	"Atmosphere": "Type IV",
	"Precipitation": 3,
	"Terrain": "gas giant",
	"Gravity": 4,
	"URL": "https://starwars.fandom.com/wiki/Yavin_Prime/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Yavin 4",
	"Region": "Outer Rim",
	"Sector": "Gordian Reach",
	"System": "Yavin",
	"Inhabitants": "Yuuzhan Vong,Chazrach,Critokian,Sith (Massassi),Terentatek,Tuk'ata,Sith wyrm,Humans",
	"Starport": 2,
	"CapitalCity": "Lost City of the Jedi,Massassi Village,Vornez",
	"Map": "P-6",
	"Climate": "temperate,tropical",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "jungle,rainforest",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Yavin_4/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Ylesia",
	"Region": "Hutt Space",
	"Sector": "Hutt Space",
	"System": "Cha Raaba",
	"Inhabitants": "Human, Hutt, Yuuzhan Vong, others",
	"Starport": 3,
	"CapitalCity": "Peace City",
	"Map": "T-12",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "island,jungle,mountain",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Ylesia/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 4,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Zygerria",
	"Region": "Outer Rim",
	"Sector": "Chorlian",
	"System": "Zygerria",
	"Inhabitants": "Zygerrians",
	"Starport": 4,
	"CapitalCity": "Royal Palace",
	"Map": "S-4",
	"Climate": "temperate",
	"Atmosphere": "Type I",
	"Precipitation": 0,
	"Terrain": "plains,mesa,highland,rocky",
	"Gravity": 1,
	"URL": "https://starwars.fandom.com/wiki/Zygerria/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 5, // Zygerrian Slave Empire
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "generic Deep Core location",
	"Region": "Deep Core",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 4,
	"CapitalCity": "Unknown",
	"Map": "L-11",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Deep_Core/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "generic Core Worlds location",
	"Region": "Core Worlds",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 5,
	"CapitalCity": "Unknown",
	"Map": "J-11",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Core_Worlds/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "generic Colonies location",
	"Region": "Colonies",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 3,
	"CapitalCity": "Unknown",
	"Map": "I-11",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Colonies/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "generic Inner Rim location",
	"Region": "Inner Rim",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 3,
	"CapitalCity": "Unknown",
	"Map": "I-12",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Inner_Rim/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "generic Expansion Region location",
	"Region": "Expansion Region",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 3,
	"CapitalCity": "Unknown",
	"Map": "H-11",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Expansion_Region/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "generic Mid Rim location",
	"Region": "Mid Rim",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 3,
	"CapitalCity": "Unknown",
	"Map": "H-11",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Mid_Rim/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "generic Hutt Space location",
	"Region": "Hutt Space",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 3,
	"CapitalCity": "Unknown",
	"Map": "T-11",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Hutt_Space/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "generic Outer Rim location",
	"Region": "Outer Rim",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 3,
	"CapitalCity": "Unknown",
	"Map": "Q-19",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Outer_Rim_Territories/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "generic Wild Space location",
	"Region": "Wild Space",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"CapitalCity": "Unknown",
	"Map": "F-18",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Wild_Space/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "generic Unknown Regions location",
	"Region": "Unknown Regions",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"CapitalCity": "Unknown",
	"Map": "G-11",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Unknown_Regions/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "generic Extragalactic location",
	"Region": "Extragalactic",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"CapitalCity": "Unknown",
	"Map": "U-20",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "https://starwars.fandom.com/wiki/Extragalactic/Legends",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "generic Unknown location",
	"Region": "Unknown",
	"Sector": "Unknown",
	"System": "Unknown",
	"Inhabitants": "Unknown",
	"Starport": 0,
	"CapitalCity": "Unknown",
	"Map": "Unknown",
	"Climate": 0,
	"Atmosphere": 0,
	"Precipitation": 0,
	"Terrain": 0,
	"Gravity": 0,
	"URL": "(unknown)",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
];
