const regions = [
{
	"Name": "Deep Core",
	"ImperialPresence": 5,
	"OldWestiness": 1,
	"Megafauna": 0,
	"Rarity": 4,
	"Criticism": -3,
	"Slavery": 1,
	"Spice": -3,
	"Trespassing": -2,
	"Military": -3,
	"Slicing": -3,
	"Theft": -2,
	"Bribery": -3,
},
{
	"Name": "Core Worlds",
	"ImperialPresence": 5,
	"OldWestiness": 0,
	"Megafauna": -5,
	"Rarity": -1,
	"Criticism": -3,
	"Slavery": -1,
	"Spice": -1,
	"Trespassing": -1,
	"Military": -3,
	"Slicing": -1,
	"Theft": -1,
	"Bribery": 0,
},
{
	"Name": "Colonies",
	"ImperialPresence": 5,
	"OldWestiness": 1,
	"Megafauna": 0,
	"Rarity": 0,
	"Criticism": -2,
	"Slavery": -2,
	"Spice": 4,
	"Trespassing": -2,
	"Military": -5,
	"Slicing": 0,
	"Theft": -1,
	"Bribery": 1,
},
{
	"Name": "Inner Rim",
	"ImperialPresence": 4,
	"OldWestiness": 2,
	"Megafauna": -4,
	"Rarity": 0,
	"Criticism": -1,
	"Slavery": -1,
	"Spice": 2,
	"Trespassing": -1,
	"Military": -3,
	"Slicing": -2,
	"Theft": -3,
	"Bribery": 0,
},
{
	"Name": "Expansion Region",
	"ImperialPresence": 3,
	"OldWestiness": 3,
	"Megafauna": -3,
	"Rarity": 0,
	"Criticism": 0,
	"Slavery": 0,
	"Spice": 3,
	"Trespassing": -1,
	"Military": -3,
	"Slicing": -1,
	"Theft": -1,
	"Bribery": 0,
},
{
	"Name": "Mid Rim",
	"ImperialPresence": 2,
	"OldWestiness": 4,
	"Megafauna": -2,
	"Rarity": 1,
	"Criticism": 1,
	"Slavery": 1,
	"Spice": 4,
	"Trespassing": -1,
	"Military": -3,
	"Slicing": -1,
	"Theft": -1,
	"Bribery": 0,
},
{
	"Name": "Outer Rim",
	"ImperialPresence": 1,
	"OldWestiness": 5,
	"Megafauna": 0,
	"Rarity": 2,
	"Criticism": 2,
	"Slavery": 2,
	"Spice": 5,
	"Trespassing": 1,
	"Military": -1,
	"Slicing": 0,
	"Theft": -1,
	"Bribery": 1,
},
{
	"Name": "Wild Space",
	"ImperialPresence": 0,
	"OldWestiness": 5,
	"Megafauna": 5,
	"Rarity": 3,
	"Criticism": 3,
	"Slavery": 2,
	"Spice": 4,
	"Trespassing": 5,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Hutt Space",
	"ImperialPresence": 1,
	"OldWestiness": 5,
	"Megafauna": 4,
	"Rarity": 2,
	"Criticism": 4,
	"Slavery": 5,
	"Spice": 5,
	"Trespassing": 3,
	"Military": -4,
	"Slicing": 1,
	"Theft": 1,
	"Bribery": 2,
},
{
	"Name": "Unknown Regions",
	"ImperialPresence": -5,
	"OldWestiness": 5,
	"Megafauna": 5,
	"Rarity": 5,
	"Criticism": 5,
	"Slavery": 5,
	"Spice": 5,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
},
{
	"Name": "Unknown",
	"ImperialPresence": 0,
	"OldWestiness": 0,
	"Megafauna": 0,
	"Rarity": 5,
	"Criticism": 5,
	"Slavery": 0,
	"Spice": 0,
	"Trespassing": 0,
	"Military": 0,
	"Slicing": 0,
	"Theft": 0,
	"Bribery": 0,
}
];
